<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Metodos Numericos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matematicas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Malaga</span>
    <br>
    <span style="font-size: small">Dpto. de Analisis Matematico, Estadistica e Investigacion Operativa, y Matematica Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Area Conocimiento de Matematica Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Seccion numero 2</span>
    </b></span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En primer lugar cargamos los modulos necesarios.
    </span></div>

In [1]:
# -*- coding: utf-8 -*-

from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El primer objetivo de esta seccion es ver la forma en la que podemos <b>definir nuestras propias funciones</b> que implementen un determinado algoritmo.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Por ejemplo, nos podemos plantear definir una funcion, a la que llamaremos <span style="font-family: Courier">conjugada()</span>, que calcule la <b>conjugada</b> de una matriz.
    <br>
  Esta funcion debe tener un unico argumento de entrada, que es una matriz $A\in\mathcal{M}_{m\times n}(\mathbb{C})$, y debe devolver su matriz conjugada $A^*\in\mathcal{M}_{n\times m}(\mathbb{C})$. El codigo necesario para llevar a cabo esta tarea puede ser tan simple como este que sigue.
    </span></div>

In [2]:
def conjugada(A):
    return conjugate(transpose(A))

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 1.</b></span>
   Calcular las conjugadas de las matrices: (a) $A = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \\ 3 & 6+6\,i \end{array} \right)$; (b) $B = \left( \begin{array}{cc} 1 & 4\,i \end{array} \right)$; (c) $C = \left( \begin{array}{c} 1 \\ 2 \\ 3 \end{array} \right)$.
    </span></div>

In [3]:
# Caso 1-a.
print("Caso 1-a.")
A = array([[1, 4j], [2, -5j], [3, 6+6j]])
print("Matriz: A = \n", A)
print("Conjugada: A^* = \n", conjugada(A))

Caso 1-a.
Matriz: A = 
 [[ 1.+0.j  0.+4.j]
 [ 2.+0.j -0.-5.j]
 [ 3.+0.j  6.+6.j]]
Conjugada: A^* = 
 [[ 1.-0.j  2.-0.j  3.-0.j]
 [ 0.-4.j -0.+5.j  6.-6.j]]


In [4]:
# Caso 1-b.
print("Caso 1-b.")
B = array([[1, 4j]])
print("Matriz: B = \n", B)
print("Conjugada: B^* = \n", conjugada(B))


Caso 1-b.
Matriz: B = 
 [[1.+0.j 0.+4.j]]
Conjugada: B^* = 
 [[1.-0.j]
 [0.-4.j]]


In [5]:
# Caso 1-c.
print("Caso 1-c.")
C = array([[1], [2], [3]])
print("Matriz: C = \n", C)
print("Conjugada: C^* = \n", conjugada(C))

Caso 1-c.
Matriz: C = 
 [[1]
 [2]
 [3]]
Conjugada: C^* = 
 [[1 2 3]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 2.</b></span>
  Mejorar la funcion anterior en el siguiente sentido: como se puede comprobar, si el argumento de entrada es un vector (array de una dimension), la funcion devuelve tambien un vector con los elementos conjugados (ello es debido a que la funcion <span style="font-family: Courier">transpose()</span> actuando sobre un vector no tiene ningun efecto); modificar la funcion creada para que en este caso considere el vector como una matriz fila y devuelva, por tanto, una matriz columna (evidentemente con los elementos conjugados).
    <br>
  Comprobar la validez de la mejora realizada utilizando el vector $x=(1+i\,,\,2-2\,i\,,\,-3+3\,i)$ (por supuesto, todo lo que funcionaba bien debera seguir funccionando bien).
    </span></div>

In [6]:
def conjugada(A):
    if (ndim(A) == 1):
        A = array([A])
    return conjugate(transpose(A))

In [7]:
# Caso 2.
print("Caso 2.")
x = array([1+1j, 2-2j, -3+3j])
print("Matriz: X = \n", x)
print("Conjugada: X^* = \n", conjugada(C))

Caso 2.
Matriz: X = 
 [ 1.+1.j  2.-2.j -3.+3.j]
Conjugada: X^* = 
 [[1 2 3]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El siguiente objetivo de esta seccion es calcular los <b>autovalores</b> y <b>autovectores</b> de una matriz, <b>diagonalizarla</b> (si es posible) y calcular sus <b>valores singulares</b>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
  Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>autovalores</b> y <b>autovectores</b> pueden calcularse con la ayuda de la funcion <span style="font-family: Courier">eig()</span>; esta funcion tiene un unico argumento de entrada que es la matriz cuadrada $A$ y tiene dos argumentos de salida, siendo el primero un vector de $n$ componentes conteniendo a los autovalores (en un orden arbitrario, quizas numeros complejos aunque la matriz sea de coeficientes reales y repetidos en caso de multiplicidad mayor que uno) y el segundo una matriz cuadrada de orden $n$ cuyas columnas son autovectores (asociados a los autovalores calculados, en el mismo orden y unitarios respecto del producto escalar ordinario).
    <br>
  No obstante la matriz de autovectores puede no ser regular en el caso de que la matriz dada no sea diagonalizable (los autovectores asociados a autovalores con multiplicidad mayor que 1 no son linealmente independientes).
    <br>
  En el caso de que la matriz dada si sea diagonalizable, la matriz de autovectores que obtenemos es regular, pero aunque tengamos asegurado que existe una matriz de paso ortogonal-unitaria (al ser la matriz dada normal), la que obtenemos no lo es necesariamente.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">

    <span style="color:#FF0000"><b>Caso 3 (a).</b></span>
  Calcular los autovalores y autovectores, y ver si es diagonalizable la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    <br>
  Imprimir el vector de autovalores y la matriz de autovectores (ortogonal-unitaria si es posible) y comprobar si la matriz dada es diagonalizable (comprobar que $P^{-1}\,A\,P=D$ para lo cual se puede utilizar la funcion <span style="font-family: Courier">inv()</span> que calcula la inversa de la funcion dada como argumento).
    </span></div>

In [8]:
# Caso 3-a.
print("Caso 3-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 3-a.
Matriz: A = 
 [[3 1]
 [0 1]]
Vector de autovalores: d =  [3. 1.]
Matriz de autovectores: P = 
 [[ 1.         -0.4472136 ]
 [ 0.          0.89442719]]
det(P) =  0.8944271909999159
La matriz es diagonalizable.
inv(P)@A@P = 
 [[3. 0.]
 [0. 1.]]
Comprobacion:  0.0


In [9]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[ 1 -2]
 [-2 -1]]
La matriz no es normal.


In [10]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.        -0.4472136]
 [-0.4472136  1.       ]]
La matriz de paso no es ortogonal-unitaria.


In [11]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  3.0  Autovector (fila): x =  [1. 0.]
Autovalor: lambda =  1.0  Autovector (fila): x =  [-0.4472136   0.89442719]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3 (b).</b></span>
  Idem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [12]:
# Caso 3-b.
print("Caso 3-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 3-b.
Matriz: A = 
 [[ 0 -2]
 [ 2  0]]
Vector de autovalores: d =  [0.+2.j 0.-2.j]
Matriz de autovectores: P = 
 [[0.        +0.70710678j 0.        -0.70710678j]
 [0.70710678+0.j         0.70710678-0.j        ]]
det(P) =  1j
La matriz es diagonalizable.
inv(P)@A@P = 
 [[0.+2.0000000e+00j 0.+4.4408921e-16j]
 [0.-4.4408921e-16j 0.-2.0000000e+00j]]
Comprobacion:  4.440892098500626e-16


In [13]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0]
 [0 0]]
La matriz es normal.


In [14]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1.00000000e+00+0.j 2.22044605e-16+0.j]
 [2.22044605e-16+0.j 1.00000000e+00+0.j]]
La matriz de paso es ortogonal-unitaria.


In [15]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  2.0000000000000004j  Autovector (fila): x =  [0.        +0.70710678j 0.70710678+0.j        ]
Autovalor: lambda =  -2.0000000000000004j  Autovector (fila): x =  [0.        -0.70710678j 0.70710678-0.j        ]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3 (c).</b></span> Idem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [16]:
# Caso 3-c.
print("Caso 3-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 3-c.
Matriz: A = 
 [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]
Vector de autovalores: d =  [ 3. -2.  1.]
Matriz de autovectores: P = 
 [[ 0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 3.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobacion:  2.220446049250313e-16


In [17]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
La matriz es normal.


In [18]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
La matriz de paso es ortogonal-unitaria.


In [19]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  3.0  Autovector (fila): x =  [0.89442719 0.         0.4472136 ]
Autovalor: lambda =  -2.0  Autovector (fila): x =  [-0.4472136   0.          0.89442719]
Autovalor: lambda =  1.0  Autovector (fila): x =  [0. 1. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3 (d).</b></span> Idem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [20]:
# Caso 3-d.
print("Caso 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 3-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P = 
 [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [21]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])


Autovalor: lambda =  1.0  Autovector (fila): x =  [0. 0. 1.]
Autovalor: lambda =  1.0  Autovector (fila): x =  [0.00000000e+00 3.17206578e-17 1.00000000e+00]
Autovalor: lambda =  1.0  Autovector (fila): x =  [2.34780031e-33 3.17206578e-17 1.00000000e+00]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3 (e).</b></span> Idem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [22]:
# Caso 3-e.
print("Caso 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 3-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 4.59534891e-17 1.00000000e+00]
Matriz de autovectores: P = 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01  6.94835567e-17  4.08248290e-01  0.00000000e+00]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00 -4.91599416e-16  8.88178420e-16  0.00000000e+00]
 [-1.74942489e-16  1.00000000e+00  9.06493304e-17  0.00000000e+00]
 [-5.06745162e-17  3.85711222e-33  2.26623326e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobacion:  8.881784197001252e-16


In [23]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
La matriz es normal.


In [24]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.00000000e+00 -7.91836773e-18  1.66533454e-16  0.00000000e+00]
 [-7.91836773e-18  1.00000000e+00  8.38776945e-17  0.00000000e+00]
 [ 1.66533454e-16  8.38776945e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
La matriz de paso es ortogonal-unitaria.


In [25]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  6.0  Autovector (fila): x =  [-0.18257419  0.          0.36514837 -0.91287093]
Autovalor: lambda =  1.0000000000000002  Autovector (fila): x =  [8.94427191e-01 0.00000000e+00 4.47213595e-01 6.94835567e-17]
Autovalor: lambda =  4.595348908876999e-17  Autovector (fila): x =  [-0.40824829  0.          0.81649658  0.40824829]
Autovalor: lambda =  1.0  Autovector (fila): x =  [0. 1. 0. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3 (f).</b></span> Idem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [26]:
# Caso 3-f.
print("Caso 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-0.8660254   0.5         0.0814746   0.23168376]
 [ 0.28867513  0.5        -0.60194778 -0.78090594]
 [ 0.28867513  0.5         0.75801897 -0.03009043]
 [ 0.28867513  0.5        -0.23754579  0.57931262]]
det(P) =  -0.9100502946314354
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  1.33226763e-15  2.22044605e-16  2.22044605e-16]
 [ 8.88178420e-16  1.00000000e+01  0.00000000e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  6.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00 -2.22044605e-16  6.00000000e+00]]
Comprobacion:  3.552713678800501e-15


In [27]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La matriz es normal.


In [28]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.00000000e+00 -5.55111512e-17 -9.40787620e-02 -2.67525357e-01]
 [-5.55111512e-17  1.00000000e+00 -2.77555756e-17 -1.66533454e-16]
 [-9.40787620e-02 -2.77555756e-17  1.00000000e+00  3.28518553e-01]
 [-2.67525357e-01 -1.66533454e-16  3.28518553e-01  1.00000000e+00]]
La matriz de paso no es ortogonal-unitaria.


In [29]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector (fila): x = ", P[:, i])

Autovalor: lambda =  6.0  Autovector (fila): x =  [-0.8660254   0.28867513  0.28867513  0.28867513]
Autovalor: lambda =  9.999999999999998  Autovector (fila): x =  [0.5 0.5 0.5 0.5]
Autovalor: lambda =  5.999999999999999  Autovector (fila): x =  [ 0.0814746  -0.60194778  0.75801897 -0.23754579]
Autovalor: lambda =  6.0  Autovector (fila): x =  [ 0.23168376 -0.78090594 -0.03009043  0.57931262]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>valores singulares</b> pueden calcularse con la ayuda de la funcion <span style="font-family: Courier">svd()</span>; esta funcion tiene un unico argumento de entrada que es la matriz cuadrada $A$ y tiene tres argumentos de salida, siendo el segundo un vector de $n$ componentes (reales y mayores o iguales que 0) conteniendo a los valores singulares (en un orden arbitrario y repetidos en caso de multiplicidad mayor que uno) y el primero y tercero las  dos matrices de orden $n$ ortogonales-unitarias de su descomposicion en valores singulares.
    <br>
    Si llamamos $S$ a la matriz diagonal cuyos elementos diagonales son los valores singulares de $A$ (en el orden que proporciona la funcion <span style="font-family: Courier">svd()</span>) y $U$ y $V$ las matrices ortogonales-unitarias que se obtienen como primera y tercera salida de dicha funcion, se verifica que $U\,S\,V=A \iff U^{-1}\,A\,V^{-1}=S$.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4 (a).</b></span> Realizar la descomposicion en valores singulares de la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    </span></div>

In [30]:
# Caso 4-a.
print("Caso 4-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposicion en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobacion: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobacion: ", max(abs(DVS1 - diag(s))))

Caso 4-a.
Matriz: A = 
 [[3 1]
 [0 1]]
Vector de valores singulares: s =  [3.1795868  0.94351882]
Matrices ortogonales-unitarias de la descomposicion en valores singulares:
U = 
 [[ 0.99402894 -0.10911677]
 [ 0.10911677  0.99402894]]
V = 
 [[ 0.93788501  0.34694625]
 [-0.34694625  0.93788501]]
U@diag(s)@V = 
 [[3.00000000e+00 1.00000000e+00]
 [1.61174921e-17 1.00000000e+00]]
Comprobacion:  8.881784197001252e-16
U^{-1}@A@V^{-1} = 
 [[ 3.17958680e+00 -1.57210765e-16]
 [ 5.69830913e-17  9.43518824e-01]]
Comprobacion:  4.440892098500626e-16


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4 (b).</b></span> Idem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [31]:
# Caso 4-b.
print("Caso 4-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposicion en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobacion: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobacion: ", max(abs(DVS1 - diag(s))))

Caso 4-b.
Matriz: A = 
 [[ 0 -2]
 [ 2  0]]
Vector de valores singulares: s =  [2. 2.]
Matrices ortogonales-unitarias de la descomposicion en valores singulares:
U = 
 [[ 0. -1.]
 [-1.  0.]]
V = 
 [[-1. -0.]
 [ 0.  1.]]
U@diag(s)@V = 
 [[ 0. -2.]
 [ 2.  0.]]
Comprobacion:  0.0
U^{-1}@A@V^{-1} = 
 [[2. 0.]
 [0. 2.]]
Comprobacion:  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4 (c).</b></span> Idem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [32]:
# Caso 4-c.
print("Caso 4-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposicion en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobacion: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobacion: ", max(abs(DVS1 - diag(s))))

Caso 4-c.
Matriz: A = 
 [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]
Vector de valores singulares: s =  [3. 2. 1.]
Matrices ortogonales-unitarias de la descomposicion en valores singulares:
U = 
 [[-0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [-0.4472136   0.89442719  0.        ]]
V = 
 [[-0.89442719  0.         -0.4472136 ]
 [ 0.4472136   0.         -0.89442719]
 [ 0.          1.          0.        ]]
U@diag(s)@V = 
 [[ 2.  0.  2.]
 [ 0.  1.  0.]
 [ 2.  0. -1.]]
Comprobacion:  1.1102230246251565e-15
U^{-1}@A@V^{-1} = 
 [[3.00000000e+00 5.20130319e-16 0.00000000e+00]
 [2.06537767e-16 2.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Comprobacion:  1.7763568394002505e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4 (d).</b></span> Idem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [33]:
# Caso 4-d.
print("Caso 4-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposicion en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobacion: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobacion: ", max(abs(DVS1 - diag(s))))

Caso 4-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de valores singulares: s =  [8.49406432 2.20182024 0.05346907]
Matrices ortogonales-unitarias de la descomposicion en valores singulares:
U = 
 [[-0.06601923  0.37536832 -0.92452154]
 [ 0.29463434 -0.87789606 -0.3774773 ]
 [-0.95332684 -0.29731656 -0.05263838]]
V = 
 [[-0.56077155  0.8203284  -0.11223447]
 [ 0.82649357  0.54651139 -0.13503217]
 [-0.0494333  -0.16848327 -0.98446419]]
U@diag(s)@V = 
 [[ 1.00000000e+00  3.91748900e-15 -5.01780125e-16]
 [-3.00000000e+00  1.00000000e+00  2.92478379e-16]
 [ 4.00000000e+00 -7.00000000e+00  1.00000000e+00]]
Comprobacion:  3.917489004022323e-15
U^{-1}@A@V^{-1} = 
 [[ 8.49406432e+00  1.69638131e-15 -4.93548397e-17]
 [-5.83349135e-16  2.20182024e+00  1.35121909e-16]
 [ 7.28380218e-16  1.06063204e-15  5.34690655e-02]]
Comprobacion:  1.696381312299903e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4 (e).</b></span> Idem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [34]:
# Caso 4-e.
print("Caso 4-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposicion en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobacion: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobacion: ", max(abs(DVS1 - diag(s))))

Caso 4-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de valores singulares: s =  [6.00000000e+00 1.00000000e+00 1.00000000e+00 5.99841267e-17]
Matrices ortogonales-unitarias de la descomposicion en valores singulares:
U = 
 [[-1.82574186e-01  8.94427191e-01 -7.13644775e-17 -4.08248290e-01]
 [ 0.00000000e+00 -2.22044605e-16 -1.00000000e+00 -2.83710209e-16]
 [ 3.65148372e-01  4.47213595e-01  0.00000000e+00  8.16496581e-01]
 [-9.12870929e-01  0.00000000e+00 -7.13644775e-17  4.08248290e-01]]
V = 
 [[-1.82574186e-01  0.00000000e+00  3.65148372e-01 -9.12870929e-01]
 [ 8.94427191e-01 -1.38777878e-16  4.47213595e-01 -5.55111512e-17]
 [-1.42728955e-16 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.08248290e-01 -8.32667268e-17 -8.16496581e-01 -4.08248290e-01]]
U@diag(s)@V = 
 [[ 1.00000000e+00 -5.27622302e-17  5.99422081e-16  1.00000000e+00]
 [-5.58737773e-17  1.00000000e+00 -9.93013661e-17  1.92735656e-32]
 [ 2.67291641e-17 -6.20633538e-17  1.000000

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4 (f).</b></span> Idem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [35]:
# Caso 4-f.
print("Caso 4-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("Vector de valores singulares: s = ", s)
print("Matrices ortogonales-unitarias de la descomposicion en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("Comprobacion: ", max(abs(DVS - A)))
DVS1 = conjugada(U)@A@conjugada(V)
print("U^{-1}@A@V^{-1} = \n", DVS1)
print("Comprobacion: ", max(abs(DVS1 - diag(s))))

Caso 4-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de valores singulares: s =  [10.  6.  6.  6.]
Matrices ortogonales-unitarias de la descomposicion en valores singulares:
U = 
 [[-5.00000000e-01  2.39306446e-17 -4.10239622e-17  8.66025404e-01]
 [-5.00000000e-01 -5.77350269e-01  5.77350269e-01 -2.88675135e-01]
 [-5.00000000e-01 -2.11324865e-01 -7.88675135e-01 -2.88675135e-01]
 [-5.00000000e-01  7.88675135e-01  2.11324865e-01 -2.88675135e-01]]
V = 
 [[-0.5        -0.5        -0.5        -0.5       ]
 [ 0.         -0.57735027 -0.21132487  0.78867513]
 [-0.          0.57735027 -0.78867513  0.21132487]
 [ 0.8660254  -0.28867513 -0.28867513 -0.28867513]]
U@diag(s)@V = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Comprobacion:  1.7763568394002505e-15
U^{-1}@A@V^{-1} = 
 [[ 1.00000000e+01 -3.43504199e-17 -4.09738790e-16  2.31030762e-15]
 [ 2.62681588e-16  6.00000000e+00  9.63291215e-16  3.67542720e-16]
 [-9.28815403e-16 -2.11030565e-1

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 5.</b></span> En aquellos casos del Caso 3 en los que hay autovalores con multiplicidad (dimension algebraica) mayor que 1, comprobar cuando la dimension geometrica de los mismos es igual o no (y por tanto la matriz es o no diagonalizable).
    <br>
    <i>Indicacion:</i> la funcion <span style="font-family: Courier">matrix_rank()</span>, cuyo parametro de entrada es una matriz (no necesariamente cuadrada), devuelve el rango de la misma.
    </span></div>

In [36]:
# Caso 5. Caso del caso 3-d.
print("Caso 5 - 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 5 - 3-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P = 
 [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]
det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [37]:
# Caso 5. Caso del caso 3-d.
da = ...
print("El autovalor 1 tiene multiplicidad (dimension algebraica) ", da)
dg = matrix_rank(P)
print("Su dimension geometrica es ", dg)
if da == dg:
    print("Por tanto la matriz es diagonalizable.")
else:
    print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimension algebraica)  Ellipsis
Su dimension geometrica es  1
Por tanto la matriz no es diagonalizable.


In [38]:
# Caso 5. Caso del caso 3-e.
print("Caso 5 - 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 5 - 3-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 4.59534891e-17 1.00000000e+00]
Matriz de autovectores: P = 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01  6.94835567e-17  4.08248290e-01  0.00000000e+00]]
det(P) =  -1.0
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00 -4.91599416e-16  8.88178420e-16  0.00000000e+00]
 [-1.74942489e-16  1.00000000e+00  9.06493304e-17  0.00000000e+00]
 [-5.06745162e-17  3.85711222e-33  2.26623326e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Comprobacion:  8.881784197001252e-16


In [39]:
# Caso 5. Caso del caso 3-e.
da = ...
print("El autovalor 1 tiene multiplicidad (dimension algebraica) ", da)
dg = matrix_rank(P[:, 1::2])
print("Su dimension geometrica es ", dg)
if da == dg:
    print("Por tanto la matriz es diagonalizable.")
else:
    print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimension algebraica)  Ellipsis
Su dimension geometrica es  2
Por tanto la matriz no es diagonalizable.


In [40]:
# Caso 5. Caso del caso 3-f.
print("Caso 5 - 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 5 - 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-0.8660254   0.5         0.0814746   0.23168376]
 [ 0.28867513  0.5        -0.60194778 -0.78090594]
 [ 0.28867513  0.5         0.75801897 -0.03009043]
 [ 0.28867513  0.5        -0.23754579  0.57931262]]
det(P) =  -0.9100502946314354
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  1.33226763e-15  2.22044605e-16  2.22044605e-16]
 [ 8.88178420e-16  1.00000000e+01  0.00000000e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  6.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00 -2.22044605e-16  6.00000000e+00]]
Comprobacion:  3.552713678800501e-15


In [41]:
# Caso 5. Caso del caso 3-f.
da = ...
print("El autovalor 1 tiene multiplicidad (dimension algebraica) ", da)
dg = matrix_rank(P[:, [0, 2, 3]])
print("Su dimension geometrica es ", dg)
if da == dg:
    print("Por tanto la matriz es diagonalizable.")
else:
    print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimension algebraica)  Ellipsis
Su dimension geometrica es  3
Por tanto la matriz no es diagonalizable.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 6.</b></span> En aquellos casos del Caso 3 en los que la matriz es normal y por tanto diagonalizable con matriz de paso unitaria, pero la matriz de paso obtenida no lo es, obtener una nueva matriz de paso que si lo sea.
    <br>
    <i>Indicacion:</i> la funcion <span style="font-family: Courier">qr()</span>, cuyo parametro de entrada es una matriz (no necesariamente cuadrada), devuelve dos matrices, siendo la primera de ellas la ortonormalizacion de Gram-Schmidt de los vectores columnas de la matriz dada.
    </span></div>

In [42]:
# Caso 6. Caso del caso 3-f.
print("Caso 6 - 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A)
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("det(P) = ", detP)
if abs(detP) > 1e-10:
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P
    print("inv(P)@A@P = \n", D)
    print("Comprobacion: ", max(abs(D - diag(d))))
else:
    print("La matriz no es diagonalizable.")

Caso 6 - 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-0.8660254   0.5         0.0814746   0.23168376]
 [ 0.28867513  0.5        -0.60194778 -0.78090594]
 [ 0.28867513  0.5         0.75801897 -0.03009043]
 [ 0.28867513  0.5        -0.23754579  0.57931262]]
det(P) =  -0.9100502946314354
La matriz es diagonalizable.
inv(P)@A@P = 
 [[ 6.00000000e+00  1.33226763e-15  2.22044605e-16  2.22044605e-16]
 [ 8.88178420e-16  1.00000000e+01  0.00000000e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  6.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00 -2.22044605e-16  6.00000000e+00]]
Comprobacion:  3.552713678800501e-15


In [43]:
# Caso 6. Caso del caso 3-f.
q, r  = qr(P[:, [0, 2, 3]])
U = array(P)
U[:, [0, 2, 3]] = q[:, :]
print("Matriz de paso ortogonal-unitaria: U = \n", U)
D = conjugada(U)@A@U
print("Diagonalizacion: U^*@A@U = \n", D)
print("Comprobacion: ", max(abs(D - diag(d))))

Matriz de paso ortogonal-unitaria: U = 
 [[-8.66025404e-01  5.00000000e-01 -5.17926092e-17 -1.29481523e-16]
 [ 2.88675135e-01  5.00000000e-01 -5.77350269e-01 -5.77350269e-01]
 [ 2.88675135e-01  5.00000000e-01  7.88675135e-01 -2.11324865e-01]
 [ 2.88675135e-01  5.00000000e-01 -2.11324865e-01  7.88675135e-01]]
Diagonalizacion: U^*@A@U = 
 [[ 6.00000000e+00  6.66133815e-16 -1.20885821e-16 -1.68959888e-16]
 [ 5.55111512e-17  1.00000000e+01 -1.08246745e-15 -2.99760217e-15]
 [ 1.24477336e-17 -9.99200722e-16  6.00000000e+00  1.11178211e-15]
 [-1.79848535e-16 -3.10862447e-15  7.17759729e-16  6.00000000e+00]]
Comprobacion:  3.552713678800501e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 7.</b></span> Para la matriz $A = \left( \begin{array}{rrr} 1 & 2 & 3 \\ 4 & 5 & 6\\ 7 & 8 & 9 \end{array} \right)$, comprobar que los valores singulares de $A$ son efectivamente las raices cuadradas positivas de los autovalores de $A^*\,A$.
    </span></div>

In [44]:
# Caso 7.
print("Caso 7.")
A = array([[1, 2 ,3], [4, 5, 6], [7, 8, 9]])
print("Matriz: A = \n", A)
U,S,V = svd(A)
print("Vector de valores singulares de A: s = ", s)
CA = conjugada(A)@A
d, P= eig(CA)
print(d)
print("Raices cuadradas de los autovalores de A^*@A:", sqrt(d))

Caso 7.
Matriz: A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector de valores singulares de A: s =  [10.  6.  6.  6.]
[2.83858587e+02 1.14141342e+00 7.28303082e-15]
Raices cuadradas de los autovalores de A^*@A: [1.68481034e+01 1.06836951e+00 8.53406751e-08]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Importante.</b></span> Durante el desarrollo de las clases practicas vamos a crear un fichero <span style="font-family: Courier">Python</span>, al que daremos el nombre de <span style="font-family: Courier">algoritmos.py</span>, donde almacenaremos todas aquellas funciones propias que definamos durante el curso; esta sera la <b>biblioteca</b> de nuestras funciones. A partir de ese momento, podremos utilizar dichas funciones en cualquier hoja de trabajo que estemos utilizando, sin mas que importar dicho fichero al principio de la hoja de trabajo con una instruccion del tipo <span style="font-family: Courier">from algoritmos import *</span>.
    <br>
    Cada vez que se modifique dicho fichero, no debemos olvidar guardar su contenido y reinicializar el nucleo de la hoja de trabajo para tener en cuenta dichas modificaciones.
    </span></div>