<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Metodos Numericos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matematicas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Malaga</span>
    <br>
    <span style="font-size: small">Dpto. de Analisis Matematico, Estadistica e Investigacion Operativa, y Matematica Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Area Conocimiento de Matematica Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Seccion numero 4</span>
    </b></span></div>

In [1]:
from algoritmos import *

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El objetivo de esta seccion es definir funciones <span style="font-family: Courier">Python</span> para resolver sistemas de ecuaciones lineales cuya matriz de coeficientes es triangular y que por tanto pueden ser resueltos mediante los <b>metodos de descenso</b> o de <b>sustitucion progresiva</b> (en el caso de matrices triangulares inferiores) y los <b>metodos de remonte</b>  o de <b>sustitucion regresiva</b> (en el caso de matrices triangulares superiores).
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Comenzamos por el caso de matrices triangulares inferiores, es decir, estudiamos los <b>metodos de descenso</b>.
    <br>
    Consideramos un sistema de $n$ ecuaciones lineales con $n$ incognitas compatible y determinado $A\,X=B$, donde $A\in\mathcal{M}_n(\mathbb{K})$ es <b>triangular inferior</b> y $X,B\in\mathbb{K}^n$, es decir,
\[
\left( \begin{array}{cccc}
a_{1,1} & & & \\
a_{2,1} & a_{2,2} & & \\
\vdots & \vdots & \ddots & \\
a_{n,1} & a_{n,2} & \cdots & a_{n,n}
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{array} \right) = \left( \begin{array}{c}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{array} \right)\,.
\]
    <br>
    El caracter compatible y determinado del sistema implica que la matriz $A$ es regular y, por tanto, $a_{i,i}\ne0$, para todo $i=1,2,\ldots,n$.
    <br>
    Estos sistemas son facilmente resolubles, pues al ser la matriz $A$ triangular inferior hace que se puedan calcular las incognitas de manera inmediata, empezando por la primera y continuando hacia abajo; esto se conoce como <b>metodo de descenso</b> o de <b>sustitucion progresiva</b>, y el algoritmo correspondiente es:
\[
\left\{ \begin{array}{ccl}
x_1 & = & \displaystyle \frac{1}{a_{1,1}}\,b_1 \\
x_i & = & \displaystyle \frac{1}{a_{i,i}}\,\left( b_i - \sum_{j=1}^{i-1} a_{i,j}\,x_j \right) \quad \mbox{para} \quad i=2,3,\ldots,n
\end{array} \right.
\]
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 1.</b></span> Definir una funcion, de nombre <span style="font-family: Courier">descenso()</span>, que implemente el algoritmo del <b>metodo de descenso</b>. Esta funcion debe tener dos argumentos de entrada, que son la matriz $A$ y el segundo miembro $B$; por otro lado debe devolver tambien dos valores, siendo el primero de tipo booleano, en la que los valores <span style="font-family: Courier">True</span> o <span style="font-family: Courier">False</span> indican que se ha resuelto o no con exito el sistema, y conteniendo el segundo valor la solucion del sistema en caso de exito o un mensaje de error en caso contrario.
    </span></div>

In [2]:
def descenso(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q != 1:
        return False, "Descenso - error : dimensiones no compatibles"
    if min(abs(diag(A))) < 1e-200:
        return False, "Descenso: matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, 1), dtype=complex)
    else:
        X = zeros((n, 1), dtype=float)
    for i in range(n):
        X[i, 0] = B[i, 0]
        if i != 0:
            X[i, 0] -= A[i, :i]@X[:i, 0]
        X[i, 0] = X[i, 0]/A[i, i]
    return True, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <b>Comentario:</b> observamos que no se hace una <b>comprobacion del caracter triangular</b> de la matriz $A$, trabajando con la parte triangular inferior e ignorando los elementos que puedan estar en la parte estrictamente triangular superior (que pueden o no ser ceros); esta estrategia se mostrara util en algoritmos futuros que usen estas funciones como parte del codigo.
    <br>
    Los <b>casos de no exito</b> en la resolucion por el metodo de descenso se limitan a un problema con las dimensiones (bien porque la matriz $A$ no sea cuadrada, bien porque el segundo miembro $B$ no tenga las dimensiones adecuadas), o tambien a que la matriz $A$ sea singular o <i>casi singular</i>; el criterio de singularidad se establece en que $\displaystyle \min_{i=1,2,\ldots,n}|a_{i,i}|<10^{-200}$.
    <br>
    Finalmente, en los <b>casos de exito</b> la solucion $X$ sera un vector de las dimensiones adecuadas de tipo real, excepto que alguno se los datos, $A$ o $B$, sea de tipo complejo, en cuyo caso sera, evidentemente, de tipo complejo tambien.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 2.</b></span> Comprobar el funcionamiento de la funcion elaborada resolviendo el sistema
\[
\left( \begin{array}{ccc}
1 & & \\
2 & 3 & \\
4 & 5 & 6
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array} \right) = \left( \begin{array}{c}
1 \\ 5 \\ 15
\end{array} \right)\,,
\]
cuya solucion es el vector con sus tres componentes iguales a 1. Comprobar el resultado verificando que $B-A\,X=0$.
    </span></div>

In [3]:
# Caso 2.
print("Caso 2.")
A = array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])
B = array([[1], [5], [15]])
exito, X = descenso(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

Caso 2.
Solucion: X =  [[1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3.</b></span> Modificar el programa anterior para prever la posibilidad de <b>resolver simultaneamente varios sistemas lineales</b> $A\,X_r=B_r$, $r=1,2,\ldots,q$, todos con la misma matriz $A$ y diferentes segundos miembros $B_r$. Es por ello que el segundo argumento de entrada del programa $B$ no es necesariamente un vector columna, sino una matriz
\[
B = \left( B_1 | B_2 | \cdots | B_q \right) \in \mathcal{M}_{n\times q}(\mathbb{K})
\]
mientras que, en caso de exito, la segunda salida del programa $X$ es tambien una matriz
\[
X = \left( X_1 | X_2 | \cdots | X_q \right) \in \mathcal{M}_{n\times q}(\mathbb{K})
\]
de las mismas dimensiones con las soluciones correspondientes.
    <br>
    En este sentido, recordamos que si $A\in\mathcal{M}_n(\mathbb{K})$ es una matriz invertible, el problema de <b>calcular su inversa</b> $A^{-1}$ es equivalente a resolver $n$ sistemas de ecuaciones lineales, todos con la misma matriz de coeficientes $A$. En efecto, si hacemos la descomposicion por bloques de la matriz inversa
\[
A^{-1} = \left( X_1 | X_2 | \cdots | X_n \right)\,,
\]
y de la matriz identidad
\[
I = \left( E_1 | E_2 | \cdots | E_n \right)\,,
\]
entonces
\[
A\,A^{-1} = I \Leftrightarrow A\,X_i = E_i \quad \mbox{para todo} \quad i=1,2,\ldots,n\,.
\]
    <br>
    En general, utilizaremos esta tecnica de resolver varios sistemas lineales de forma simultanea <b>siempre</b> que el algoritmo lo permita.
    </span></div>

In [3]:
def descenso(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Descenso - error : error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Descenso - error : matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((m, q), dtype=complex)
    else:
        X = zeros((m, q), dtype=float)
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, :] -= A[i, :i]@X[:i, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4.</b></span> Comprobar el funcionamiento de la modificacion realizada en el programa calculando la inversa de la matriz
\[
A = \left( \begin{array}{ccc}
1 & & \\
2 & 3 & \\
4 & 5 & 6
\end{array} \right)\,.
\]
Comprobar tambien el resultado verificando que $A\,A^{-1}=I$.
    </span></div>

In [5]:
A = array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])
B = eye(3)
exito, X = descenso(A, B)
if exito:
    print("Inversa: A^{-1} = ", X)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(B-A@X, 2))
else:
    print(X)

Inversa: A^{-1} =  [[ 1.          0.          0.        ]
 [-0.66666667  0.33333333  0.        ]
 [-0.11111111 -0.27777778  0.16666667]]
Comprobacion: ||I-A@A^{-1}||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Consideramos ahora el caso de matrices triangulares superiores, es decir, estudiamos los <b>metodos de remonte</b>.
    <br>
    Consideramos un sistema de $n$ ecuaciones lineales con $n$ incognitas compatible y determinado $A\,X=B$, donde $A\in\mathcal{M}_n(\mathbb{K})$ es <b>triangular superior</b> y $X,B\in\mathbb{K}^n$, es decir,
\[
\left( \begin{array}{cccc}
a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
& a_{2,2} & \cdots & a_{2,n} \\
& & \ddots & \vdots \\
& & & a_{n,n}
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{array} \right) = \left( \begin{array}{c}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{array} \right)\,.
\]
    <br>
    Aqui tambien el caracter compatible y determinado del sistema implica que la matriz $A$ es regular y, por tanto, $a_{i,i}\ne0$, para todo $i=1,2,\ldots,n$.
    <br>
    Estos sistemas son facilmente resolubles, pues al ser la matriz $A$ triangular superior hace que se puedan calcular las incognitas de manera inmediata, empezando ahora por la ultima y continuando hacia arriba; esto se conoce como <b>metodo de remonte</b> o de <b>sustitucion regresiva</b>, y el algoritmo correspondiente es:
\[
\left\{ \begin{array}{ccl}
x_n & = & \displaystyle \frac{1}{a_{n,n}}\,b_n \\
x_i & = & \displaystyle \frac{1}{a_{i,i}}\,\left( b_i - \sum_{j=i+1}^n a_{i,j}\,x_j \right) \quad \mbox{para} \quad i=n-1,n-2,\ldots,1
\end{array} \right.
\]
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 5.</b></span> Definir una funcion, de nombre <span style="font-family: Courier">remonte()</span>, que implemente el algoritmo del <b>metodo de remonte</b>. Esta funcion debe tener las mismas caracteristicas que el programa <span style="font-family: Courier">descenso()</span>.
    <br>
    <b>Comentario:</b> para generar un contador que retroceda, se puede utilizar la instruccion <span style="font-family: Courier">range(a,b,c)</span> que genera una lista de enteros desde <span style="font-family: Courier">a</span> (incluido) hasta <span style="font-family: Courier">b</span> (excluido), con salto de <span style="font-family: Courier">c</span> (que puede ser negativo).
    </span></div>

In [4]:
def remonte(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error remonte: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error remonte: matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    for i in range(n-1,-1,-1):
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] -= A[i, i+1:]@X[i+1:, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 6.</b></span> Comprobar el funcionamiento de la funcion elaborada resolviendo el sistema
\[
\left( \begin{array}{ccc}
1 & 2 & 3\\
& 4 & 5 \\
& & 6
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array} \right) = \left( \begin{array}{c}
6 \\ 9 \\ 6
\end{array} \right)\,,
\]
cuya solucion es el vector con sus tres componentes iguales a 1. Calcular tambien la inversa de la matriz de coeficientes y comprobar los resultados obtenidos.
    </span></div>

In [7]:
A = array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
B = array([[6], [9], [6]])
exito, X = remonte(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)
    print()
    
C = eye(3)
exitoI, Y = remonte(A, C)
if exitoI:
    print("Inversa: A^{-1} = ", Y)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(C-A@Y, 2))
else:
    print(Y)

Solucion: X =  [[1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0
Inversa: A^{-1} =  [[ 1.         -0.5        -0.08333333]
 [ 0.          0.25       -0.20833333]
 [ 0.          0.          0.16666667]]
Comprobacion: ||I-A@A^{-1}||_2 =  0.0


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Problema.</b></span> Resolver los siguientes sistemas de ecuaciones lineales:
\[
\begin{array}{lllll}
\mbox{(a)} & \left( \begin{array}{rrrr}
5 & & & \\ 1 & 3 & & \\ 3 & 4 & 2 & \\ -1 & 3 & -6 & -1
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
-10 \\ 4 \\ 2 \\ 5
\end{array} \right) & \mbox{} &
\mbox{(b)} & \left( \begin{array}{rrrr}
2 & & & \\ -1 & 4 & & \\ 3 & -2 & -1 & \\ 1 & -2 & 6 & 3
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
6 \\ 5 \\ 4 \\ 2
\end{array} \right) \\
\mbox{} \\
\mbox{(c)} & \left( \begin{array}{rrrr}
4 & -1 & 2 & 3 \\ & -2 & 7 & -4 \\ & & 6 & 5 \\ & & & 3
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
20 \\ -7 \\ 4 \\ 6
\end{array} \right) & \mbox{} &
\mbox{(d)} & \left( \begin{array}{rrrr}
3 & -2 & 1 & -1 \\ & 4 & -1 & 2 \\ & & 2 & 3 \\ & & & 5
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
8 \\ -3 \\ 11 \\ 15
\end{array} \right)
\end{array}
\]
    <br><br>
    Como tarea adicional se pide:
<ul>
    <li> comprobar la exactitud de los resultados obtenidos;</li>
    <li> calcular las inversas de las matrices de coeficientes y comprobar la exactitud de los resultados;</li>
    <li> en algun caso, cambiar alguna dimension en la matriz de coeficientes o en el segundo miembro, de manera que se provoque una situacion de error;</li>
    <li> el algun caso, cambiar a 0 (o a un numero muy proximo a 0) el valor de un elemento diagonal de la matriz de coeficientes, de manera que se provoque una situacion de error;</li>
    <li> en algun caso, cambiar el valor de algunos de los elementos que deben ser 0 en una matriz triangular, por otros valores distintos de 0 de manera que la matriz deje de ser triangular; observar como los programas obvian estos valores y resuelven los sistemas como si las matrices fueran triangulares (si se hace la comprobacion de la exactitud de los resultados se detectara este problema);</li>
    <li> cambiar algunos de los elementos de la matriz de coeficientes y/o del segundo miembro por numeros complejos para comprobar que los programas funcionan con aritmetica compleja.</li>
</ul>
    </span></div>

In [8]:
A = array([[5,0,0,0],[1,3,0,0],[3,4,2,0],[-1,3,-6,-1]])
B = array([[-10],[4],[2],[5]])
exito, X = descenso(A, B)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)
    print()

C = eye(4)
exitoI, Y = descenso(A, C)

if exitoI:
    print("Inversa: A^{-1} = ", Y)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(C-A@Y, 2))
else:
    print(Y)
    print()
    
A2 = array([[5,0,0,0],[1,3,0,0],[3,4,2,0],[-1,3,-6,-1],[1,0,0,0]])
exito2, X = descenso(A2, B)

if exito2:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A2@X, 2))
else:
    print(X)
    print()
    
A3 = array([[5,0,0,0],[1,3,0,0],[3,4,0,0],[-1,3,-6,-1]])
exito3, X = descenso(A3, B)

if exito3:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A3@X, 2))
else:
    print(X)
    print()
    
A4 = array([[5,0,0,27],[1,3,0,0],[3,4,2,0],[-1,3,-6,-1]])
exito4, X = descenso(A4, B)

if exito4:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A4@X, 2))
else:
    print(X)
    print()


A5 = array([[5,0,0,0],[1+0j,3,0,0],[3,4,2,0],[-1,3,-6,-1]])
B2 = array([[-10],[4+0j],[2],[5]])
exito5, X = descenso(A5, B2)

if exito5:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B2-A5@X, 2))
else:
    print(X)

Solucion: X =  [[-2.]
 [ 2.]
 [ 0.]
 [ 3.]]
Comprobacion: ||B-A@X||_2 =  0.0
Inversa: A^{-1} =  [[ 0.2         0.          0.          0.        ]
 [-0.06666667  0.33333333  0.          0.        ]
 [-0.16666667 -0.66666667  0.5         0.        ]
 [ 0.6         5.         -3.         -1.        ]]
Comprobacion: ||I-A@A^{-1}||_2 =  0.0
Descenso - error : error en las dimensiones.

Descenso - error : matriz singular.

Solucion: X =  [[-2.]
 [ 2.]
 [ 0.]
 [ 3.]]
Comprobacion: ||B-A@X||_2 =  6561.0
Solucion: X =  [[-2.+0.j]
 [ 2.+0.j]
 [ 0.+0.j]
 [ 3.-0.j]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 7.</b></span> Elaborar dos nuevas funciones, a las que daremos el nombre de <span style="font-family: Courier,monospace">descenso1()</span> y <span style="font-family: Courier,monospace">remonte1()</span>, respectivamente, que implementen los mismos <b>metodos de descenso y remonte</b>, pero suponiendo ahora que la matriz de coeficientes $A$ tiene <b>1 en la diagonal principal</b> (independientemente de los valores que esten guardados en los elementos diagonales de la matriz que se pasa como argumento a las funciones creadas). Estos programas seran de utilidad en la fase final de resolucion de un sistema lineal por metodos de descomposicion.
    <br><br>
    <span style="color:#FF0000"><b>Comentario.</b></span> Para realizar los programas anteriores, unicamente hay que tener en cuenta que los elementos diagonales de las matrices solamente aparecen en la division final del algoritmo, por lo que <i>suprimir esa division</i> es equivalente a <i>dividir por 1</i>. Por otro lado no sera necesario en este caso la comprobacion sobre el caracter regular de la matriz, puesto que estamos suponiendo que los elementos diagonales valen 1 (independientemente de los valores que se encuentren almacenados en dichas posiciones) y por tanto la matriz es siempre inversible.
    </span></div>

In [5]:
def descenso1(A, B):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error descenso: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((m, q), dtype=complex)
    else:
        X = zeros((m, q), dtype=float)
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, :] -= A[i, :i]@X[:i, :]
    return True, X

In [6]:
def remonte1(A, B):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error remonte: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((m, q), dtype=complex)
    else:
        X = zeros((m, q), dtype=float)
    for i in range(n-1,-1,-1):
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] -= A[i, i+1:]@X[i+1:, :]
    return True, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 8.</b></span> Resolver los siguientes sistemas de ecuaciones lineales:
\[
\begin{array}{lllll}
\mbox{(a)} & \left( \begin{array}{rrrr}
1 & & & \\ 1 & 1 & & \\ 3 & 4 & 1 & \\ -1 & 3 & -6 & 1
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
-10 \\ 4 \\ 2 \\ 5
\end{array} \right) & \mbox{} &
\mbox{(b)} & \left( \begin{array}{rrrr}
1 & -1 & 2 & 3 \\ & 1 & 7 & -4 \\ & & 1 & 5 \\ & & & 1
\end{array} \right) \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
20 \\ -7 \\ 4 \\ 6
\end{array} \right)
\end{array}
\]
    <br><br>
    Dado que ambas matrices tienes elementos diagonales iguales a 1, resolver los sistemas utilizando tanto los metodos generales de <span style="font-family: Courier,monospace">descenso()</span> y <span style="font-family: Courier,monospace">remonte()</span>, respectivamente, como los metodos modificados de <span style="font-family: Courier,monospace">descenso1()</span> y <span style="font-family: Courier,monospace">remonte1()</span>, viendo que se obtienen los mismos resultados.
    </span></div>

In [41]:
A = array([[1, 0, 0, 0], [1, 1, 0, 0], [3, 4, 1, 0], [-1, 3, -6, 1]])
B = array([[-10], [4], [2], [5]])
exito, X = descenso1(A, B)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

exito1, Y = descenso1(A, B)

if exito1:
    print("Solucion: X = ", Y)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@Y, 2))
else:
    print(X)

Solucion: X =  [[ -10.]
 [  14.]
 [ -24.]
 [-191.]]
Comprobacion: ||B-A@X||_2 =  0.0
Solucion: X =  [[ -10.]
 [  14.]
 [ -24.]
 [-191.]]
Comprobacion: ||B-A@X||_2 =  0.0


In [7]:
A = array([[1, -1, 2, 3], [0, 1, 7, -4], [0, 0, 1, 5], [0, 0, 0, 1]])
B = array([[20], [-7], [4], [6]])
exito, X = remonte(A, B)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

exito1, Y = remonte1(A, B)
if exito1:
    print("Solucion: X = ", Y)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@Y, 2))
else:
    print(X)

Solucion: X =  [[253.]
 [199.]
 [-26.]
 [  6.]]
Comprobacion: ||B-A@X||_2 =  0.0
Solucion: X =  [[253.]
 [199.]
 [-26.]
 [  6.]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    Otro caso particularmente interesante se produce cuando la <b>matriz triangular</b> $A$ es, al mismo tiempo, <b>tridiagonal</b>, lo que significa que realmente sus unicos elementos no nulos pueden estar situados en dos diagonales: la diagonal principal y una diagonal adicional, bien la sub-diagonal en el caso de triangulares inferiores, bien la supra-diagonal en el caso de triangulares superiores. Una <b>resolucion optima</b> de estos sistemas evita aquellos calculos inutiles al involucrar los muchos 0 que existen.
    </span></div>

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 9.</b></span> Elaborar dos nuevas funciones, a las que daremos el nombre de <span style="font-family: Courier,monospace">descenso_1diag()</span> y <span style="font-family: Courier,monospace">remonte_1diag()</span>, respectivamente, que implementen la <b>mejora de tiempo de calculo</b> descrita en el parrafo anterior para <b>matrices triangulares y tridiagonales</b>. Estos programas seran similares a los anteriores en cuanto a argumentos de entrada y de salida y tampoco haran una comprobacion sobre el caracter tridiagonal de la matriz, suponiendo que son nulos los elementos que deben serlo, independientemente de los valores que esten guardados en dichas posiciones de la matriz.
    </span></div>

In [8]:
def descenso_1diag(A, B):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error descenso: error en las dimensiones."
    
    if min(abs(diag(A))) < 1e-200:
        return False, "Error descenso: matriz singular."
    if A.dtype == complex or B.dtype == complex:
        X = zeros((m, q), dtype=complex)
    else:
        X = zeros((m, q), dtype=float)
        
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, :] -= A[i, i-1]*X[i-1, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X

In [9]:
def remonte_1diag(A, B):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error remonte: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error remonte: matriz singular."
        
    if A.dtype == complex or B.dtype == complex:
        X = zeros((m, q), dtype=complex)
    else:
        X = zeros((m, q), dtype=float)
    
    for i in range(n-1,-1,-1):
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] -= A[i, i+1]*X[i+1, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 10.</b></span> Crear una matriz de orden 5, triangular inferior (superior) y tridiagonal, que tenga en la diagonal principal 2 y en la sub-diagonal (supra-diagonal) $-1$; crear igualmente un segundo miembro adecuado para que la solucion del sistema lineal correspondiente sea el vector con todos sus elementos igual a 1 (esto se consigue tomando como segundo miembro el vector cuyos elementos son las sumas de los elementos de las filas correspondientes de la matriz de coeficientes).
    <br><br>
    Resolver ese sistema lineal con la funcion que implementa el metodo de descenso (remonte) completo y el que implementa el metodo correspondiente optimizado para matrices tridiagonales, comprobando que se obtienen resultados similares.
    </span></div>

In [35]:
A = 2*eye(5) - eye(5, k=-1)
B = reshape(sum(A, axis=1), (5, 1))
print(A)
exito, X = descenso_1diag(A,B)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

[[ 2.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.]
 [ 0.  0. -1.  2.  0.]
 [ 0.  0.  0. -1.  2.]]
Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0


In [12]:
A = 2*eye(5) - eye(5, k=1)
B = reshape(sum(A, axis=1), (5, 1))
print(A)
exito, X = descenso_1diag(A,B)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

[[ 2. -1.  0.  0.  0.]
 [ 0.  2. -1.  0.  0.]
 [ 0.  0.  2. -1.  0.]
 [ 0.  0.  0.  2. -1.]
 [ 0.  0.  0.  0.  2.]]
Solucion: X =  [[0.5]
 [0.5]
 [0.5]
 [0.5]
 [1. ]]
Comprobacion: ||B-A@X||_2 =  1.3228756555322954


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 11.</b></span> Calcular las inversas de las matrices del caso anterior, comprobando que dichas inversas no conservan el caracter tridiagonal de la matriz inicial.
    </span></div>

In [32]:
A = 2*eye(5) - eye(5, k=-1)
B = eye(5)
exitoI, Y = descenso_1diag(A, B)

if exitoI:
    print("Inversa: A^{-1} = ", Y)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(B-A@Y, 2))
else:
    print(Y)

Inversa: A^{-1} =  [[0.5     0.      0.      0.      0.     ]
 [0.25    0.5     0.      0.      0.     ]
 [0.125   0.25    0.5     0.      0.     ]
 [0.0625  0.125   0.25    0.5     0.     ]
 [0.03125 0.0625  0.125   0.25    0.5    ]]
Comprobacion: ||I-A@A^{-1}||_2 =  0.0


In [13]:
A = 2*eye(5) - eye(5, k=1)
B = eye(5)
exitoI, Y = remonte_1diag(A, B)

if exitoI:
    print("Inversa: A^{-1} = ", Y)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(B-A@Y, 2))
else:
    print(Y)

Inversa: A^{-1} =  [[0.5     0.25    0.125   0.0625  0.03125]
 [0.      0.5     0.25    0.125   0.0625 ]
 [0.      0.      0.5     0.25    0.125  ]
 [0.      0.      0.      0.5     0.25   ]
 [0.      0.      0.      0.      0.5    ]]
Comprobacion: ||I-A@A^{-1}||_2 =  0.0


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 12.</b></span> Se puede <b>controlar el tiempo de ejecucion</b> de un programa importando la funcion <span style="font-family: Courier,monospace">time()</span> del modulo <span style="font-family: Courier,monospace">time</span>, haciendo una llamada a dicha funcion antes y despues de ejecutar el programa que queramos controlar y calculando la diferencia de tiempos.
    <br><br>
    Analizar la diferencia de tiempos de ejecucion de la version general del programa <span style="font-family: Courier,monospace">descenso()</span> (respect. <span style="font-family: Courier,monospace">remonte()</span>) y del programa <span style="font-family: Courier,monospace">descenso_1diag()</span> (respect. <span style="font-family: Courier,monospace">remonte_1diag()</span>), usando un sistema lineal analogo al del Caso 10, pero de tamano tan grande como sea posible.
    </span></div>

In [16]:
from time import time
n = 15000
A = 2*eye(n) - eye(n, k=-1)
B = reshape(sum(A, axis=1), (n, 1))

tiempo_ini = time()
exito, X = descenso(A, B)
tiempo_fin = time()

if exito:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
    print(tiempo_fin-tiempo_ini)
else:
    print(X)
    
tiempo_ini = time()
exito, X = descenso_1diag(A, B)
tiempo_fin = time()

if exito:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
    print(tiempo_fin-tiempo_ini)
else:
    print(X)

Comprobacion: ||B-A@X||_2 =  0.0
0.09490466117858887
Comprobacion: ||B-A@X||_2 =  0.0
0.07554888725280762


In [15]:
from time import time
n = 15000
A = 2*eye(n) - eye(n, k=1)
B = reshape(sum(A, axis=1), (n, 1))

tiempo_ini = time()
exito, X = descenso(A, B)
tiempo_fin = time()

if exito:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
    print(tiempo_fin-tiempo_ini)
else:
    print(X)
    
tiempo_ini = time()
exito, X = descenso_1diag(A, B)
tiempo_fin = time()

if exito:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
    print(tiempo_fin-tiempo_ini)
else:
    print(X)

Comprobacion: ||B-A@X||_2 =  61.241325916410396
0.07292628288269043
Comprobacion: ||B-A@X||_2 =  61.241325916410396
0.06452345848083496


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 13.</b></span> Al igual que para las matrices triangulares y tridiagonales (es decir, matrices banda con semi-anchura de la banda $r=1$) hemos elaborado funciones optimizadas de los algoritmos de descenso y de remonte respectivamente, elaborar funciones similares para el caso de <b>matrices banda con semi-anchura de la banda $r$</b> ($1\le r<n$).
    <br><br>
    Utilizar los nombres de <span style="font-family: Courier,monospace">descenso_rdiag()</span> y <span style="font-family: Courier,monospace">remonte_rdiag()</span> para dichas funciones, que deben tener un parametro de entrada adicional que es justamente el valor de $r$.
    <br><br>
    Observamos que en el caso $r=n-1$ la matriz es realmente llena, si bien el caracter de matriz banda se utiliza cuando $r$ es <i>pequeno<i> en comparacion con $n$.
    </span></div>

In [57]:
def descenso_rdiag(A, B, r):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1 or r >= n:
        return False, "Descenso - err : Dimensiones no compatibles."
    if min(abs(diag(A))) < 1e-200:
        return False, "Descenso - error : matriz singular."
        
    if A.dtype == complex or B.dtype == complex:
        X = zeros((m, q), dtype=complex)
    else:
        X = zeros((m, q), dtype=float)
        
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
            X[i, :] -= A[i, max([i-r, 0]):i]@X[max([i-r,0]):i, :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X

In [60]:
def remonte_rdiag(A, B, r):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error remonte: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error remonte: matriz singular."
        
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
    
    for i in range(n-1,-1,-1):
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] -= A[i, i+1:min([i+r+1,n])]@X[i+1:min([i+r+1,n]), :]
        X[i, :] = X[i, :]/A[i, i]
    return True, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 14.</b></span> Crear una matriz de orden 5, pentadiagonal inferior (superior) y tridiagonal, que tenga en la diagonal principal 4 y en las dos sub-diagonales (supra-diagonales) $-1$; crear igualmente un segundo miembro adecuado para que la solucion del sistema lineal correspondiente sea el vector con todos sus elementos igual a 1.
    <br><br>
    Resolver ese sistema lineal con la funcion que implementa el metodo de descenso (remonte) completo y el que implementa el metodo correspondiente optimizado para matrices $r$-bandas, comprobando que se obtienen resultados similares.
    </span></div>

In [58]:
A = 4*eye(5) - eye(5, k=-1) - eye(5, k=-2)
B = reshape(sum(A, axis=1), (5, 1))

print(A)
print()
print(B)
print()

exito, X = descenso(A, B)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)
    print()
    
exito, X = descenso_rdiag(A, B, 3)

if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

[[ 4.  0.  0.  0.  0.]
 [-1.  4.  0.  0.  0.]
 [-1. -1.  4.  0.  0.]
 [ 0. -1. -1.  4.  0.]
 [ 0.  0. -1. -1.  4.]]

[[4.]
 [3.]
 [2.]
 [2.]
 [2.]]

Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0
Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0


In [61]:
A = 4*eye(5) - eye(5, k=1) - eye(5, k=2)
B = reshape(sum(A, axis=1), (5, 1))

print(A)
print()
print(B)
print()

exito, X = remonte(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)
    print()
    
exito, X = remonte_rdiag(A, B, 3)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

[[ 4. -1. -1.  0.  0.]
 [ 0.  4. -1. -1.  0.]
 [ 0.  0.  4. -1. -1.]
 [ 0.  0.  0.  4. -1.]
 [ 0.  0.  0.  0.  4.]]

[[2.]
 [2.]
 [2.]
 [3.]
 [4.]]

Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0
Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Comentario.</b></span> Consideremos de nuevo el caso de una matriz invertible $A\in\mathcal{M}_n(\mathbf{K})$ triangular inferior y tridiagonal. Es habitual que para el <b>almacenamiento</b> de la misma en la memoria del ordenador, no se utilice una matriz de tamano $n\times n$ (cuyos elementos serian en su mayoria 0), sino que se utilice una <i>matriz optimizada</i> de tamano $n\times2$, en cuya segunda columna se almacenan los elementos de la diagonal principal conservando la fila, y en cuya primera columna se almacenan los elementos de la sub-diagonal tambien conservando la fila (el valor almacenada en la primera fila y primera columna de esta <i>matriz optimizada</i> no tiene ninguna utilidad en este caso). En el caso de matrices triangulares superiores se almacena la diagonal principal en la primera columna, mientras que en la segunda columna se almacenan los elementos de la supra-diagonal, siempre conservando la fila (en este caso el valor almacenado en la segunda columna de la ultima fila no tiene ninguna utilidad).
    <br><br>
    Otras tecnicas similares se utilizan, en general, para el almacenamiento de <b>matrices vacias</b>.
    </span></div>

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 15.</b></span> Modificar nuestro programa <span style="font-family: Courier,monospace">descenso_1diag()</span> creando un nuevo programa de nombre <span style="font-family: Courier,monospace">descenso_1diag_vacia()</span> que tenga en cuenta esta forma optimizada de almacenamiento de la matriz. Realizar un analisis similar para el caso de matrices triangulares superiores, pasando del programa <span style="font-family: Courier,monospace">remonte_1diag()</span> al programa <span style="font-family: Courier,monospace">remonte_1diag_vacia()</span>.

In [66]:
def descenso_1diag_vacia(A, B):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error descenso: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error descenso: matriz singular."
        
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
        Y = zeros((n, 2), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
        Y = zeros((n, 2), dtype=float)
        
    for i in range(n):
        if i!=0:
            Y[i,0] = A[i,i-1]
            Y[i,1] = A[i,i]
        else:
            Y[i,1] = A[i,i]
            
    for i in range(n):
        X[i, :] = B[i, :]
        if i != 0:
             X[i, :] -= Y[i, 0]*X[i-1, :]
        X[i, :] = X[i, :]/Y[i, 1]
    return True, X

In [67]:
def remonte_1diag_vacia(A, B):
    m, n = shape(A)
    p, q = shape(B)
    
    if m != n or n != p or q < 1:
        return False, "Error remonte: error en las dimensiones."
    if min(abs(diag(A))) < 1e-200:
        return False, "Error remonte: matriz singular."
    
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype=complex)
        Y = zeros((n, 2), dtype=complex)
    else:
        X = zeros((n, q), dtype=float)
        Y = zeros((n, 2), dtype=float)
    
    for i in range(n):
        if i!=n-1:
            Y[i,1] = A[i,i+1]
            Y[i,0] = A[i,i]
        else:
            Y[i,0] = A[i,i]
    
    for i in range(n-1,-1,-1):
        X[i, :] = B[i, :]
        if i != n-1:
            X[i, :] -= Y[i, 1]*X[i+1, :]
        X[i, :] = X[i, :]/Y[i, 0]
    return True, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 16.</b></span> Crear una matriz de orden $n$ (con $n$ suficientemente grande), triangular inferior (superior) y tridiagonal, que tenga en la diagonal principal 2 y en la sub-diagonal (supra-diagonal) $-1$; crear igualmente un segundo miembro adecuado para que la solucion del sistema lineal correspondiente sea el vector con todos sus elementos igual a 1.
    <br><br>
    Resolver ese sistema lineal con la funcion que implementa el metodo de descenso (remonte) completo, el que implementa el metodo de descenso (remonte) optimizado para matrices triadiagonales y el que implementa el metodo correspondiente optimizado para matrices tridiagonales y para el almacenamiento optimizado de la matriz, comprobando que se obtienen resultados similares.
    </span></div>

In [68]:
n = 15000
A = 2*eye(n) - eye(n, k=-1)
B = reshape(sum(A, axis=1), (n, 1))

exito, X = descenso(A, B)
if exito:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)
    print()
    
exito2, X = descenso_1diag_vacia(A, B)
if exito2:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

Comprobacion: ||B-A@X||_2 =  0.0
Comprobacion: ||B-A@X||_2 =  0.0


In [69]:
n = 15000
A = 2*eye(n) - eye(n, k=1)
B = reshape(sum(A, axis=1), (n, 1))

exito, X = remonte(A, B)
if exito:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)
    print()
    
exito2, X = remonte_1diag_vacia(A, B)
if exito2:
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print(X)

Comprobacion: ||B-A@X||_2 =  0.0
Comprobacion: ||B-A@X||_2 =  0.0
