<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Metodos Numericos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matematicas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Malaga</span>
    <br>
    <span style="font-size: small">Dpto. de Analisis Matematico, Estadistica e Investigacion Operativa, y Matematica Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Area Conocimiento de Matematica Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Seccion numero 5</span>
    </b></span></div>

In [8]:
from algoritmos import *

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El objetivo de esta seccion es definir funciones <span style="font-family: Courier">Python</span> para resolver sistemas de ecuaciones lineales por <b>metodos directos de tipo Gauss</b>.
    <br>
    Suponemos por tanto dadas $A\in\mathcal{M}_n(\mathbb{K})$ inversible y $B\in\mathbb{K}^n$, y desarrollamos metodos numericos para calcular $X\in\mathbb{K}^n$ tal que $A\,X = B$.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El <b>metodo de Gauss</b> es un <b>metodo directo</b> de resolucion del problema anterior que, formalmente, equivale a calcular una matriz $M\in\mathcal{M}_n(\mathbb{K})$ inversible tal que la matriz $M\,A$ sea <b>triangular superior</b> y, posteriormente, resolver el sistema $(M\,A)\,X = (M\,B)$ mediante un <b>metodo de remonte</b>.
    <br>
    En la seccion no se calcula dicha matriz $M$, sino que se va <i>triangularizando</i> la matriz $A$ mediante un <b>proceso iterativo</b> de $n-1$ etapas, en cada una de las cuales, tras colocar en la posicion diagonal correspondiente un elemento no nulo (<b>pivote</b> de la iteracion), se van haciendo nulos a traves de adecuadas combinaciones lineales todos los elementos de la columna situados por debajo de la diagonal principal.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    De manera similar, el <b>metodo de Gauss-Jordan</b> es un <b>metodo directo</b> de resolucion del mismo problema que, formalmente, equivale a calcular una matriz $M\in\mathcal{M}_n(\mathbb{K})$ inversible tal que la matriz $M\,A$ sea <b>diagonal</b> y, posteriormente, resolver el sistema $(M\,A)\,X = (M\,B)$ que es inmediato debido al caracter diagonal de la matriz.
    <br>
    Tampoco aqui en la seccion se calcula dicha matriz $M$, sino que se va <i>diagonalizando</i> la matriz $A$ mediante un <b>proceso iterativo</b> de $n$ etapas, en cada una de las cuales, tras colocar en la posicion diagonal correspondiente un elemento no nulo (<b>pivote</b> de la iteracion), se van haciendo nulos a traves de adecuadas combinaciones lineales todos los elementos de la columna excepto, evidentemente, el situado en la diagonal principal.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En ambos metodos tiene particular importancia la eleccion del elemento que en cada iteracion ocupa la posicion de pivote; las dos tecnicas mas habituales son la de <b>pivote parcial</b> y la de <b>primer pivote no nulo</b>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Nos planteamos entonces como primer objetivo elaborar cuatro funciones <span style="font-family: Courier">Python</span>, a las que daremos los nombres de <span style="font-family: Courier">gauss_pp()</span> y <span style="font-family: Courier">gauss_1p()</span>, para el <b>metodo de Gauss</b>, y <span style="font-family: Courier">gaussjordan_pp()</span> y <span style="font-family: Courier">gaussjordan_1p()</span>, para el de <b>Gauss-Jordan</b>, que implementan ambos algoritmos con las dos <b>tecnicas de eleccion de pivote</b> indicadas anteriormente.
    <br>
    En todos los casos habra dos <b>argumentos de entrada</b>, que son la matriz $A$ y el segundo miembro $B$, y como <b>salida</b> se obtienen tambien dos variables, siendo la primera de tipo booleano, en la que los valores <span style="font-family: Courier">True</span> o <span style="font-family: Courier">False</span> indica que se ha resuelto con exito o no el sistema, y conteniendo la segunda variable la solucion o un mensaje de error, respectivamente.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En todas las funciones que desarrollemos se intentara utilizar la misma terminologia y nombre de las variables que se ha visto en clases teoricas y de problemas; de esta manera es posible seguir mejor la programacion del algoritmo correspondiente. En cualquier caso, resaltamos los siguientes hechos:
    <ul>
    <li>siempre se trabaja con la idea de que las funciones puedan resolver multiples sistemas lineales, todos con la misma matriz $A$, de manera simultanea, por lo que supondremos que $B$, y en consecuencia $X$ tambien, no es un vector de $\mathbb{K}^n$, sino un matriz de $\mathcal{M}_{n\times q}(\mathbb{K})$;</li>
    <li> el bucle principal del proceso iterativo se realiza en la variable <span style="font-family: Courierc">k</span>; recordamos que hay $n-1$ iteraciones en el metodo de Gauss y $n$ en el de Gauss-Jordan;</li>
    <li> siempre que se haga referencia a las filas de las matrices se utiliza preferentemente el indice <span style="font-family: Courier">i</span>, mientras que para las columnas se utiliza el indice <span style="font-family: Courier">j</span>;</li>
    <li>la fila en la que se localiza la posicion del pivote de cada iteracion (dependiendo de la estrategia utilizada), se identifica con el indice <span style="font-family: Courier">ik</span>;</li>
    <li>son facilmente identificables las instrucciones que permutan las filas de la matriz y del segundo miembro, en el caso de que el pivote de la iteracion no se encuentre en la posicion natural;</li>
    <li>el proceso de hacer ceros por debajo de la diagonal (y por encima tambien en el caso de Gauss-Jordan), se realiza unicamente si el pivote elegido es mayor o igual en modulo que $10^{-200}$, que es el umbral de precision elegido;</li>
    <li>en cada iteracion solamente se calculan los elementos de la matriz y del segundo miembro que cambian, no realizandose ningun calculo superfluo;</li>
    <li>en las posiciones que deberian anularse en la iteracion $k$-esima, es decir, $a_{i,k}^{k+1}$, para $i=k+1,\ldots,n$, (en el caso de Gauss-Jordan tambien para $i=1,\ldots,k-1$) no se guardan ceros, sino que se almacenan los cocientes $\displaystyle\frac{\alpha_{i,k}^k}{\alpha_{k,k}^k}$, que son los elementos no nulos y no diagonales de la matrix de combinaciones lineales $E_k$ con signo cambiado;</li>
    <li>en el metodo de Gauss, el proceso de resolucion del (de los) sistema(s) se realiza mediante una llamada al programa <span style="font-family: Courier">remonte()</span>, que seria el que detectaria, si fuera el caso, la existencia de elementos nulos (o casi nulos) en la diagonal principal, es decir, detectaria si la matriz es o no regular;</li>
    <li>en el metodo de Gauss-Jordan, la resolucion del (de los) sistema(s), es decir las $n$ divisiones de los elementos del (de los) segundo(s) miembro(s) por los elementos diagonales de $M\,A$, se realiza en el propio codigo, previa comprobacion de que dichos elementos diagonales superen el umbral de precision elegido.</li>
    </ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 1.</b></span> Elaborar un programa de nombre <span style="font-family: Courier">gauss_pp()</span> que implemente el algoritmo del <b>metodo de Gauss</b>, con estrategia de <b>pivote parcial</b>, teniendo en cuenta las observaciones anteriores.
    </span></div>

In [ ]:
def gauss_pp(A, B):
    m, n = shape(A)
    p, q = shape(B)

    if m != n or n != p or q < 1:
        return False, "Error gauss_pp: error en las dimensiones."

    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)

    for k in range(n-1):
        # Returns the indices of the maximum values
        pos = argmax(abs(gaussA[k:, k]))
        ik = pos+k

        # Si ik = k el pivot se encuentra incialmente en la fila correcta
        if ik != k:
            # Hacemos la permutacion oportuna ya que el pivot escogido no es el que se encuentra inicialmente
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]


        # Si no se verifica el if, toda la columna es nula (practicamente)
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                # Operamos elemento diagonal
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]

                # Operamos todo lo que queda por debajo de la diagonal en la columna oportuna
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]

                # Operamos identicamente en la matriz B (en este caso incluyendo la diagonal)
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]

    # Resolvemos el sistema con las matrices diagonales superiores o inferiores
    exito, X = remonte(gaussA, gaussB)
    return exito, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 2.</b></span> Elaborar un programa de nombre <span style="font-family: Courier">gaussjordan_pp()</span> que implemente el algoritmo del <b>metodo de Gauss-Jordan</b>, con estrategia de <b>pivote parcial</b>, teniendo en cuenta las observaciones anteriores.
    </span></div>

In [ ]:
def gaussjordan_pp(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_jordan_pp: error en las dimensiones."

    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)

    for k in range(n):
        pos = argmax(abs(gaussA[k:, k]))
        ik = pos+k
        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]

        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]

            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]


    #if min(abs(diag(A))) < 1e-200:
    #    return False, "Error: matriz singular."
    #if B.dtype == complex:
    #    X = array(gaussB, dtype=complex)
    #else:
    #    X = array(gaussB, dtype=float)

    X = copy(gaussB)

    d = diag(gaussA)
    d = reshape(d, (n,1))
    X = X / d

    return True, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3.</b></span> Resolver los siguientes sistemas de ecuaciones lineales mediante los metodos de Gauss y de Gauss-Jordan, con estrategias de pivote parcial:
\[
\mbox{(a)} \quad \left( \begin{array}{rrrr}
1 & 2 & 1 & 4 \\ 2 & 0 & 4 & 3 \\ 4 & 2 & 2 & 1 \\ -3 & 1 & 3 & 2
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
13 \\ 28 \\ 20 \\ 6
\end{array} \right) \qquad \mbox{(b)} \quad \left( \begin{array}{rrrr}
20514 & 4424 & 978 & 224 \\ 4424 & 978 & 224 & 54 \\ 978 & 224 & 54 & 14 \\ 224 & 54 & 14 & 4
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) =  \left( \begin{array}{r}
20514 \\ 4424 \\ 978 \\ 224
\end{array} \right)
\]
    </span></div>

In [3]:
# Caso 3-a.
print("Caso 3-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)

B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)

exito, X = gauss_pp(A, B)
if exito:
    print("Solucion: X = \n", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)


print()
exito, X = gaussjordan_pp(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Caso 3-a.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
Solucion: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]
Comprobacion: ||B-A@X||_2 =  0.0

Solucion: X =  [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]
Comprobacion: ||B-A@X||_2 =  0.0


In [4]:
# Caso 3-b.
print("Caso 3-b.")

A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)

B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)

exito, X = gaussjordan_pp(A, B)
if exito:
    print("Solucion: X = \n", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Caso 3-b.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
Solucion: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4.</b></span> Calcular las inversas de las matrices de los sistemas anteriores.
    </span></div>

In [ ]:
# Caso 4-a.
print("Caso 4-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = eye(4)

exito, X = gauss_pp(A, B)
if exito:
    print("Inversa: A^{-1} = ", X)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(B-A@X, 2))
else:
    print(X)

exito, X = gaussjordan_pp(A, B)
if exito:
    print("Solucion: X = \n", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_mat(B-A@X, 2))
else:
    print("Error ", X)

Caso 4-a.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Inversa: A^{-1} =  [[-1.38777878e-17  8.33333333e-02  8.33333333e-02 -1.66666667e-01]
 [ 6.66666667e-02 -3.44444444e-01  3.22222222e-01  2.22222222e-01]
 [-2.00000000e-01  1.16666667e-01  1.16666667e-01  1.66666667e-01]
 [ 2.66666667e-01  1.22222222e-01 -2.11111111e-01 -1.11111111e-01]]
Comprobacion: ||I-A@A^{-1}||_2 =  2.744338023001029e-16
Solucion: X = 
 [[ 0.          0.08333333  0.08333333 -0.16666667]
 [ 0.06666667 -0.34444444  0.32222222  0.22222222]
 [-0.2         0.11666667  0.11666667  0.16666667]
 [ 0.26666667  0.12222222 -0.21111111 -0.11111111]]
Comprobacion: ||B-A@X||_2 =  2.0033270179132086e-16


In [ ]:
# Caso 4-b.
print("Caso 4-b.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)

exito, X = gauss_pp(A, B)
if exito:
    print("Inversa: A^{-1} = ", X)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(B-A@X, 2))
else:
    print(X)
    print()

exito, X = gaussjordan_pp(A, B)
if exito:
    print("Inversa: A^{-1} = ", X)
    print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(B-A@X, 2))
else:
    print(X)

Caso 4-b.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Inversa: A^{-1} =  [[-1.38777878e-17  8.33333333e-02  8.33333333e-02 -1.66666667e-01]
 [ 6.66666667e-02 -3.44444444e-01  3.22222222e-01  2.22222222e-01]
 [-2.00000000e-01  1.16666667e-01  1.16666667e-01  1.66666667e-01]
 [ 2.66666667e-01  1.22222222e-01 -2.11111111e-01 -1.11111111e-01]]
Comprobacion: ||I-A@A^{-1}||_2 =  2.744338023001029e-16
Inversa: A^{-1} =  [[ 0.          0.08333333  0.08333333 -0.16666667]
 [ 0.06666667 -0.34444444  0.32222222  0.22222222]
 [-0.2         0.11666667  0.11666667  0.16666667]
 [ 0.26666667  0.12222222 -0.21111111 -0.11111111]]
Comprobacion: ||I-A@A^{-1}||_2 =  2.0033270179132086e-16


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 5.</b></span> Para el caso (a) del Caso 3, escribir el sistema final triangular superior resultante $(M\,A)\,X = M\,B$ cuando se utiliza el metodo de Gauss. Identificar tambien las matrices $A_k$ y segundos miembros $B_k$, $k=1,2,\ldots,n$ del proceso iterativo.
    </span></div>

In [ ]:
def gauss_verbose_pp(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_pp: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        pos = argmax(abs(gaussA[k:, k]))
        ik = pos+k
        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
    exito, X = remonte(gaussA, gaussB)


    print("Matriz MA: \n", triu(gaussA))
    print("Matriz MB: \n", gaussB)

    return exito, X

In [ ]:
# Caso 5-a.
print("Caso 5-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
exito, X = gauss_verbose_pp(A, B)
if exito:
    print("Solucion: X = \n", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Caso 5-a.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
Matriz MA: 
 [[4.   2.   2.   1.  ]
 [0.   2.5  4.5  2.75]
 [0.   0.   4.8  3.6 ]
 [0.   0.   0.   3.75]]
Matriz MB: 
 [[20. ]
 [21. ]
 [26.4]
 [ 7.5]]
Solucion: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 6.</b></span> Para el caso (a) del Caso 3, escribir el sistema final diagonal resultante $(M\,A)\,X = M\,B$ cuando se utiliza el metodo de Gauss-Jordan. Identificar tambien las matrices $A_k$ y segundos miembros $B_k$, $k=1,2,\ldots,n+1$ del proceso iterativo.
    </span></div>

In [ ]:
def gaussjordan_verbose_pp(A, B):
    m, n = shape(A)
    p, q = shape(B)

    if m != n or n != p or q < 1:
        return False, "Error gauss_jordan_pp: error en las dimensiones."

    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)

    for k in range(n):
        pos = argmax(abs(gaussA[k:, k]))
        ik = pos+k

        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]

        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]

            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]


    #    if min(abs(diag(A))) < 1e-200:
    #         return False, "Error: matriz singular."
    # if B.dtype == complex:
    #     X = array(gaussB, dtype=complex)
    #    else:
    #        X = array(gaussB, dtype=float)

    X = copy(gaussB)

    d = diag(gaussA)
    d = reshape(d, (n,1))
    X = X / d



    print("Matriz MA: \n", diag(gaussA))
    print("Matriz MB: \n", gaussB)

    return True, X

In [ ]:
# Caso 6-a.
print("Caso 6-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
exito, X = gaussjordan_pp_verbose(A, B)
if exito:
    print("Solucion: X = \n", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 7.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gaus_1p()</span> que implemente el algoritmo del <b>metodo de Gauss</b>, con estrategia de <b>primer pivote no nulo</b>.
    </span></div>

In [ ]:
def gauss_1p(A, B):
    m, n = shape(A)
    p, q = shape(B)

    if m != n or n != p or q < 1:
        return False, "Error gauss_pp: error en las dimensiones."

    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)

    for k in range(n-1):
        for ik in range(k, n-1):
            if (abs(gaussA[ik,k]) > 1e-200): break;

        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]

        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
    exito, X = remonte(gaussA, gaussB)
    return exito, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 8.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gausjordan_1p()</span> que implemente el algoritmo del <b>metodo de Gauss-Jordan</b>, con estrategia de <b>primer pivote no nulo</b>.
    </span></div>

In [ ]:
def gaussjordan_1p(A, B):
    m, n = shape(A)
    p, q = shape(B)

    if m != n or n != p or q < 1:
        return False, "Error gauss_jordan_pp: error en las dimensiones."

    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)

    for k in range(n):

        for ik in range(n-1, k-1 , -1):
            if (abs(gaussA[ik,k]) > 1e-200): break;

        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]

        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]

            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]


    #if min(abs(diag(A))) < 1e-200:
    #    return False, "Error: matriz singular."
    #if B.dtype == complex:
    #    X = array(gaussB, dtype=complex)
    #else:
    #    X = array(gaussB, dtype=float)

    X = copy(gaussB)

    d = diag(gaussA)
    d = reshape(d, (n,1))
    X = X / d

    return True, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Caso 9.</b></span> Resolver los sistemas de ecuaciones lineales del caso 3 mediante los metodos de Gauss y de Gauss-Jordan, con estrategias de primer pivote no nulo.
    </span></div>

In [ ]:
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
...

In [7]:
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
e, X = gaussjordan_1p(A,B)
print(X)

Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
[[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]
