<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Metodos Numericos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matematicas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Malaga</span>
    <br>
    <span style="font-size: small">Dpto. de Analisis Matematico, Estadistica e Investigacion Operativa, y Matematica Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Area Conocimiento de Matematica Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Seccion numero 6</span>
    </b></span></div>

In [2]:
from algoritmos import *

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El objetivo de esta seccion es definir funciones <span style="font-family: Courier">Python</span> para resolver sistemas de ecuaciones lineales utilizando para ello <b>factorizaciones</b> de tipo $LU$ y de Cholesky.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Recordamos que dada $A\in\mathcal{M}_n(\mathbb{K})$ inversible, se llama <b>factorizacion</b> $LU$ a la descomposicion, si es posible, $A=L\,U$, siendo $L\in\mathcal{M}_n(\mathbb{K})$ triangular inferior, inversible y con unos en la diagonal principal y $U\in\mathcal{M}_n(\mathbb{K})$ triangular superior e inversible. Esta factorizacion es posible si y solamente si todas las submatrices principales de $A$ son tambien inversibles, siendo ademas unica.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    La factorizacion $LU$ de una matriz $A$, cuando es posible, esta asociada de forma natural a un metodo directo de resolucion del sistema $AX=B$, llamado <b>metodo</b> $LU$, en el que se pueden diferenciar dos etapas:<ul>
    <li>determinacion de la factorizacion $A=L\,U$ de la matriz;</li>
    <li>resolucion mediante un proceso de descenso seguido de uno de remonte del sistema lineal, ya que
\[
A\,X = B\quad \Longleftrightarrow\quad L\,Y = B \quad \mbox{y} \quad U\,X=Y\,.
\]</li></ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 1.</b></span> Escribir una funcion <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">facto_lu()</span>, que implemente el algoritmo de la <b>factorizacion</b> $LU$ de una matriz $A$. Recordamos que realizar la factorizacion $LU$ de una matriz es equivalente a realizar el metodo de Gauss sin permutacion de filas en cada iteracion; la funcion debe prever que la matriz dada verifique las hipotesis necesarias para que dicha factorizacion sea posible.
    <br>
    Dicha funcion debe tener un unico argumento de entrada, que es la matriz $A$ y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha realizado o no dicha factorizacion) y el segundo una unica matriz que debe contener en la parte triangular superior la matriz $U$ y en la parte estrictamente triangular inferior la matrz $L$ (cuyos elementos diagonales, que valen 1, no se guardan).
    </span></div>

In [3]:
def facto_lu(A):
    m, n = shape(A)

    if m != n:
        return False, "Error Factorizacion LU: error en las dimensiones."

    if A.dtype == complex:
        lu = array(A, dtype=complex)
    else:
        lu = array(A, dtype=float)

    for k in range(n-1):
        if abs(lu[k, k]) < 1e-200:
            return False, "Error facto_lu: no existe la factorizacion, no posible division."
        else:
            for i in range(k+1, n):
                lu[i, k] = lu[i, k]/lu[k, k]
                lu[i, k+1:] -= lu[i, k]*lu[k, k+1:]

    return True, lu

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 2.</b></span> Realizar, si es posible, la factorizacion $LU$ de las siguientes matrices:
\[
\mbox{(a)} \quad A = \left(\begin{array}{rrrr} 2 & -1 & 4 & 0 \\ 4 & -1 & 5 & 1 \\ -2 & 2 & -2 & 3 \\ 0 & 3 & -9 & 4 \end{array} \right)\,;
\qquad
\mbox{(b)} \quad A = \left(\begin{array}{rrrr} 3 & -2 & 6 & -5 \\ 18 & -12 & 41 & -39 \\ -27 & 18 & -62 & 54 \\ 9 & 14 & 15 & -47 \end{array} \right)\,.
\]
    Comprobar la exactitud de los calculos realizados, verificando que $A-L\,U=0$.
    </span></div>

In [4]:
# Caso 2-a.
print("Caso 2-a.")
A = array([[2, -1, 4, 0], [4, -1, 5, 1], [-2, 2, -2, 3], [0, 3, -9, 4]])
print("Matriz: A = ", A)
exito, lu = facto_lu(A)
if exito:
    print("Factorizacion: lu = ", lu)
    U = triu(lu)
    print("Matriz: U = ", U)
    L = eye(4) + tril(lu, k=-1)
    print("Matriz: L = ", L)
    print("Comprobacion: ||A-L@U||_2 = ", norma_mat(A - L@U, 2))
else:
    print("Error ", lu)

Caso 2-a.
Matriz: A =  [[ 2 -1  4  0]
 [ 4 -1  5  1]
 [-2  2 -2  3]
 [ 0  3 -9  4]]
Factorizacion: lu =  [[ 2. -1.  4.  0.]
 [ 2.  1. -3.  1.]
 [-1.  1.  5.  2.]
 [ 0.  3.  0.  1.]]
Matriz: U =  [[ 2. -1.  4.  0.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  5.  2.]
 [ 0.  0.  0.  1.]]
Matriz: L =  [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [-1.  1.  1.  0.]
 [ 0.  3.  0.  1.]]
Comprobacion: ||A-L@U||_2 =  0.0


In [7]:
# Caso 2-b.
print("Caso 2-b.")
A = array([[3, -2, 6, -5], [18, -12, 41, -39], [-27, 18, -62, 54], [9, 14, 15, -47]])
print("Matriz: A = ", A)

exito, lu = facto_lu(A)
if exito:
    print("Factorizacion: lu = ", lu)
    U = triu(lu)
    print("Matriz: U = ", U)
    L = eye(4) + tril(lu, k=-1)
    print("Matriz: L = ", L)
    print("Comprobacion: ||A-L@U||_2 = ", norma_mat(A - L@U, 2))
else:
    print("Error ", lu)

Caso 2-b.
Matriz: A =  [[  3  -2   6  -5]
 [ 18 -12  41 -39]
 [-27  18 -62  54]
 [  9  14  15 -47]]
Error  Error facto_lu: no existe la factorizacion.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3.</b></span> Escribir una funcion <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">metodo_lu()</span>, que implemente el algoritmo del <b>metodo</b> $LU$ para resolver un sistema lineal $A\,X=B$.
    <br>
    Dicha funcion debe tener dos argumentos de entrada, que son la matriz $A$ y el(los) segundo(s) miembro(s) $X$, y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha resuelto o no el sistema) y el segundo la(s) solucion(ones) del sistema en caso de exito o un mensaje de error en caso contrario.
    </span></div>

In [11]:
def metodo_lu(A, B):
  m, n = shape(A)
  p, q = shape(B)

  if m != n or n != p or q < 1:
    return False, "Error metodo LU: Dimensiones no comptabiles."

  exito, lu = facto_lu(A)
  if exito:
    e, Y = descenso1(lu,B)
    t, X = remonte(lu,Y)
    return True, X
  else:
    return False, "Error metodos LU: error en la resolucion."

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4.</b></span> Resolver mediante el metodo $LU$, si es posible, los siguientes sistemas lineales:
\[
\mbox{(a)} \quad \left(\begin{array}{rrrr} 2 & -1 & 4 & 0 \\ 4 & -1 & 5 & 1 \\ -2 & 2 & -2 & 3 \\ 0 & 3 & -9 & 4 \end{array} \right) \left( \begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array} \right) =  \left( \begin{array}{r} 5 \\ 9 \\ 1 \\ -2 \end{array} \right)\,;
\qquad
\mbox{(b)} \quad \left(\begin{array}{rrrr} 3 & -2 & 6 & -5 \\ 24 & -12 & 41 & -39 \\ -27 & 18 & -62 & 54 \\ 9 & 14 & 15 & -47 \end{array} \right) \left( \begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array} \right) =  \left( \begin{array}{r} 1 \\ 1 \\ 1 \\ 1 \end{array} \right)\,.
\]
    Comprobar la exactitud de los calculos realizados, verificando que $B-A\,X=0$.
    <br>
    Calcular tambien,cuando sea posible, las inversas de las matrices dadas mediante el metodo $LU$.
    </span></div>

In [15]:
# Caso 4-a.
print("Caso 4-a.")
A = array([[2, -1, 4, 0], [4, -1, 5, 1], [-2, 2, -2, 3], [0, 3, -9, 4]])
print("Matriz: A = ", A)
B = array([[5], [9], [1], [-2]])
print("Segundo miembro: B = ", B)
exito, X = metodo_lu(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B - A@X, 2))
else:
    print("Error ", X)


C = eye(4)
exito, X = metodo_lu(A,C)
if exito:
  print("Inversa: A^{-1} = ", X)
  print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(C-A@X, 2))
else:
  print("Error ", X)

Caso 4-a.
Matriz: A =  [[ 2 -1  4  0]
 [ 4 -1  5  1]
 [-2  2 -2  3]
 [ 0  3 -9  4]]
Segundo miembro: B =  [[ 5]
 [ 9]
 [ 1]
 [-2]]
Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0
Inversa: A^{-1} =  [[ -2.6   1.5  -0.1  -0.3]
 [-13.4   7.    0.6  -2.2]
 [ -1.8   1.    0.2  -0.4]
 [  6.   -3.    0.    1. ]]
Comprobacion: ||I-A@A^{-1}||_2 =  3.69087570942304e-15


In [16]:
# Caso 4-b.
print("Caso 4-b.")
A = array([[3, -2, 6, -5], [18, -12, 41, -39], [-27, 18, -62, 54], [9, 14, 15, -47]])
print("Matriz: A = ", A)
B = array([[1], [1], [1], [1]])
print("Segundo miembro: B = ", B)
exito, X = metodo_lu(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B - A@X, 2))
else:
    print("Error ", X)

# No posible al no admitir la factorizacion
#C = eye(4)
#exito, X = metodo_lu(A,C)
#if exito:
#  print("Inversa: A^{-1} = ", X)
#  print("Comprobacion: ||I-A@A^{-1}||_2 = ", norma_mat(C-A@X, 2))
#else:
# print("Error ", X)

Caso 4-b.
Matriz: A =  [[  3  -2   6  -5]
 [ 18 -12  41 -39]
 [-27  18 -62  54]
 [  9  14  15 -47]]
Segundo miembro: B =  [[1]
 [1]
 [1]
 [1]]
Error  Error metodos LU: error en la resolucion.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Recordamos ahora que dada $A\in\mathcal{M}_n(\mathbb{R})$ simetrica e inversible, se llama <b>factorizacion de Cholesky</b> a la descomposicion, si es posible, $A=C\,C^t$, siendo $C\in\mathcal{M}_n(\mathbb{R})$ triangular inferior e inversible. Esta factorizacion es posible si y solamente si la matriz $A$ es definida positiva, siendo ademas unica si se impone que los elementos diagonales de $C$ sean positivos.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    La factorizacion de Cholesky de una matriz $A$, cuando es posible, esta asociada de forma natural a un metodo directo de resolucion del sistema $AX=B$, llamado <b>metodo de Cholesky</b>, en el que se pueden diferenciar dos etapas:<ul>
    <li>determinacion de la factorizacion de Cholesky $A=C\,C^t$ de la matriz;</li>
    <li>resolucion mediante un proceso de descenso seguido de uno de remonte del sistema lineal, ya que
\[
A\,X = B\quad \Longleftrightarrow\quad C\,Y = B \quad \mbox{y} \quad C^t\,X=Y\,.
\]</li></ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 5.</b></span> Escribir una funcion <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">facto_cholesky()</span>, que implemente el algoritmo de la <b>factorizacion de Cholesky</b> de una matriz $A$. Recordamos que para optimizar el numero de operaciones que conducen a dicha factorizacion, utilizando el caracter simetrico de la matriz $A$, es importante hacer una impementacion correcta de la relacion
\[
a_{i,j} = \sum_{k=1}^i c_{i,k}\,c_{j,k}, \quad 1 \le i \le j \le n\,.
\]
    Haciendo $i=1,2,\ldots,n$ sucesivamente permite calcular las columnas de la matriz $C$.
    <br>
    La funcion creada debe tener un unico argumento de entrada, que es la matriz $A$ y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha realizado o no dicha factorizacion) y el segundo una unica matriz que debe contener en la parte triangular inferior la matriz $C$ y en la parte triangular superior la matrz $C^t$ (cuyos elementos diagonales son los mismos de los de la matriz $C$).
    </span></div>

In [17]:
def facto_cholesky(A):
    m, n = shape(A)

    if m != n:
        return False, "Error facto_cholesky: Dimensiones no compatibles."

    if A.dtype == complex:
        return False, "Error facto_cholesky: matriz compleja."
    else:
      # Matriz Cholesky
        c = array(A, dtype=float)

    for i in range(n):
        c[i, i] -= sum(power(c[i, 0:i], 2))

        if c[i, i] >= 1e-100:
            c[i, i] = sqrt(c[i, i])
        else:
            return False, "Error facto_cholesky: no se factoriza la matriz"

      # Se sigue desarrollo de los apuntes
        for j in range(i+1, n):
            c[j, i] -= sum(c[i, 0:i]*c[j, 0:i])
            c[j, i] = c[j, i]/c[i, i]
            c[i, j] = c[j, i] # Por simetria

    return True, c

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 6.</b></span> Realizar, si es posible, la factorizacion de Cholesky de las siguientes matrices:
\[
\mbox{(a)} \quad A = \left(\begin{array}{rrrr} 1 & 2 & 3 & 4 \\ 2 & 5 & 1 & 10 \\ 3 & 1 & 35 & 5 \\ 4 & 10 & 5 & 45 \end{array} \right)\,;
\qquad
\mbox{(b)} \quad A = \left(\begin{array}{rrrr} 1 & 2 & 1 & 1 \\ 2 & 3 & 4 & 3 \\ 1 & 4 & -4 & 0 \\ 1 & 3 & 0 & 0 \end{array} \right)\,.
\]
    Comprobar la exactitud de los calculos realizados, verificando que $A-C\,C^t=0$.
    </span></div>

In [23]:
# Caso 6-a.
print("Caso 6-a.")
A = array([[1, 2, 3, 4], [ 2, 5, 1, 10], [ 3, 1, 35, 5], [ 4, 10, 5, 45]])
B = array([[10],[18],[44],[64]])

print("Matriz: A = ", A)
exito, chol = facto_cholesky(A)
if exito:
    print("Factorizacion: chol = ", chol)
    C = tril(chol)
    print("Matriz: C = ", C)
    print("Comprobacion: ||A-C@C^t||_2 = ", norma_mat(A - C@transpose(C), 2))
else:
    print("Error ", chol)


# Esta definido en una celda posterior
exito, X = metodo_cholesky(A, B)
if exito:
  print("Solucion: X = ", X)
  print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
  print("Error ", X)


Caso 6-a.
Matriz: A =  [[ 1  2  3  4]
 [ 2  5  1 10]
 [ 3  1 35  5]
 [ 4 10  5 45]]
Factorizacion: chol =  [[ 1.  2.  3.  4.]
 [ 2.  1. -5.  2.]
 [ 3. -5.  1.  3.]
 [ 4.  2.  3.  4.]]
Matriz: C =  [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3. -5.  1.  0.]
 [ 4.  2.  3.  4.]]
Comprobacion: ||A-C@C^t||_2 =  0.0
Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0


In [19]:
# Caso 6-b.
print("Caso 6-b.")
A = array([[1, 2, 1, 1], [ 2, 3, 4, 3], [ 1, 4, -4, 0], [ 1, 3, 0, 0]])
print("Matriz: A = ", A)
...

Caso 6-b.
Matriz: A =  [[ 1  2  1  1]
 [ 2  3  4  3]
 [ 1  4 -4  0]
 [ 1  3  0  0]]


Ellipsis

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 7.</b></span> Para las matrices del caso anterior, cuando sea posible, construir segundos miembros adecuados para que la solucion del sistema resultante sea el vector de todas sus componentes iguales a 1 y resolver el sistema mediante el metodo de Cholesky.
    <br>
    Sera necesario, previamente, escribir una funcion <span style="font-family: Courier">Python</span>, de nombre <span style="font-family: Courier">metodo_cholesky()</span>, que implemente el algoritmo del <b>metodo de Cholesky</b> para resolver un sistema lineal $A\,X=B$.
    <br>
    Dicha funcion debe tener dos argumentos de entrada, que son la matriz $A$ y el(los) segundo(s) miembro(s) $X$, y dos argumentos de salida, siendo el primero de tipo boleano (para indicar si se ha resuelto o no el sistema) y el segundo la(s) solucion(ones) del sistema en caso de exito o un mensaje de error en caso contrario.
    </span></div>

In [21]:
def metodo_cholesky(A, B):
  m, n = shape(A)
  p, q = shape(B)

  if m != n or n != p or q < 1:
    return False, "Error metodo Cholesky: Dimensiones no compatibles."

  d, chol = facto_cholesky(A)
  if exito:
    t, Y = descenso(chol,B)
    p, X = remonte(chol,Y)
    return True, X
  else:
    return False, "Error metodo Cholesky: error en la resolucion."

In [22]:
# Caso 7-a.
print("Caso 7-a.")
A = array([[1, 2, 3, 4], [ 2, 5, 1, 10], [ 3, 1, 35, 5], [ 4, 10, 5, 45]])
print("Matriz: A = ", A)
B = reshape(sum(A, axis=1), (4, 1))
print("Segundo miembro: B = ", B)
exito, X = metodo_cholesky(A, B)
if exito:
    print("Solucion: X = ", X)
    print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B - A@X, 2))
else:
    print("Error ", X)

Caso 7-a.
Matriz: A =  [[ 1  2  3  4]
 [ 2  5  1 10]
 [ 3  1 35  5]
 [ 4 10  5 45]]
Segundo miembro: B =  [[10]
 [18]
 [44]
 [64]]
Solucion: X =  [[1.]
 [1.]
 [1.]
 [1.]]
Comprobacion: ||B-A@X||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 8.</b></span> Considerar las matrices de Hilbert de orden $n=5,6,7,\ldots$, y tomar como segundo miembro la suma de las columnas de A. Evidentemente la solucion del sistema resultante es el vector con todas las componentes igual a 1. Resolver los sistemas con el metodo de Cholesky y ver que ocurre. (Observacion: se puede demostrar que las matrices de Hilbert son simetricas y definidas positivas, por lo que admiten dicha factorizacion.)

Nota: Las matrices de Hilbert se caracterizan porque el patron de generacion de sus elementos responde a la siguiente estructura:

$$H_{i,j}=\frac{1}{i+j-1}$$

$$
H_4=\begin{pmatrix} 1&\frac{1}{2}&\frac{1}{3}&\frac{1}{4}\\
\frac{1}{2}&\frac{1}{3}&\frac{1}{4}&\frac{1}{5}\\
\frac{1}{3}&\frac{1}{4}&\frac{1}{5}&\frac{1}{6}\\
\frac{1}{4}&\frac{1}{5}&\frac{1}{6}&\frac{1}{7}
\end{pmatrix}
$$
    </span></div>

In [24]:
def hilbert(n):
  H = zeros((n,n))
  for i in range(n):
    for j in range(n):
      H[i,j] = 1/((i+1)+(j+1)-1)
  return H

In [26]:
# Caso 8.
print("Caso 8.")
H5 = hilbert(5)
H6 = hilbert(6)
H7 = hilbert(7)
H10 = hilbert(10)
H20 = hilbert(20)
b5 = sum(H5,axis=0)
B5 = reshape(b5,(size(b5),1))
b6 = sum(H6,axis=0)
B6 = reshape(b6,(size(b6),1))
b7 = sum(H7,axis=0)
B7 = reshape(b7,(size(b7),1))
b10 = sum(H10,axis=0)
B10 = reshape(b10,(size(b10),1))
b20 = sum(H20,axis=0)
B20 = reshape(b20,(size(b20),1))

Caso 8.


In [28]:
""" print(H5)
exito, chol = facto_cholesky(H5)
if exito:
  print("Factorizacion: chol = ", chol)
  C = tril(chol)
  print("Matriz: C = ", C)
  print("Comprobacion: ||H5-C@C^t||_2 = ", norma_mat(H5 - C@transpose(C
else:
  print("Error ", chol)
  print()
exito, X = metodo_cholesky(H5, B5)
if exito:
  print("Solucion: X = ", X)
  print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B5-H5@X, 2))
else:
  print("Error ", X)
  print()
  print(H6)
exito, chol = facto_cholesky(H6)
if exito:
  print("Factorizacion: chol = ", chol)
  C = tril(chol)
  print("Matriz: C = ", C)
  print("Comprobacion: ||H6-C@C^t||_2 = ", norma_mat(H6 - C@transpose(C
else:
  print("Error ", chol)
  print()
exito, X = metodo_cholesky(H6, B6)
if exito:
  print("Solucion: X = ", X)
  print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B6-H6@X, 2))
else:
  print("Error ", X)
  print()
"""

' print(H5)\nexito, chol = facto_cholesky(H5)\nif exito:\n  print("Factorizacion: chol = ", chol)\n  C = tril(chol)\n  print("Matriz: C = ", C)\n  print("Comprobacion: ||H5-C@C^t||_2 = ", norma_mat(H5 - C@transpose(C\nelse:\n  print("Error ", chol)\n  print()\nexito, X = metodo_cholesky(H5, B5)\nif exito:\n  print("Solucion: X = ", X)\n  print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B5-H5@X, 2))\nelse:\n  print("Error ", X)\n  print()\n  print(H6)\nexito, chol = facto_cholesky(H6)\nif exito:\n  print("Factorizacion: chol = ", chol)\n  C = tril(chol)\n  print("Matriz: C = ", C)\n  print("Comprobacion: ||H6-C@C^t||_2 = ", norma_mat(H6 - C@transpose(C\nelse:\n  print("Error ", chol)\n  print()\nexito, X = metodo_cholesky(H6, B6)\nif exito:\n  print("Solucion: X = ", X)\n  print("Comprobacion: ||B-A@X||_2 = ", norma_vec(B6-H6@X, 2))\nelse:\n  print("Error ", X)\n  print()\n'