<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Metodos Numericos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matematicas - Curso 2023/24</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Malaga</span>
    <br>
    <span style="font-size: small">Dpto. de Analisis Matematico, Estadistica e Investigacion Operativa, y Matematica Aplicada</span>
    <br>
    <span style="font-size: medium; color:#000000">Profs. Manuel J. Castro y Francisco J. Palma (Area Conocimiento de Matematica Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Seccion numero 9</span>
    </b></span></div>

In [ ]:
from algoritmos import *

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000">
    El objetivo de esta seccion es desarrollar programas <span style="font-family: Courier">Python</span> para calcular autovalores y autovectores de matrices mediante el <span style="color:#FF0000"><b>metodo de la potencia</b></span> y sus <span style="color:#FF0000"><b>variantes</b></span>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Recordamos que el algoritmo del <b>metodo de la potencia</b> para calcular el <b>autovalor dominante</b>, y la <b>direccion de un autovector</b> asociado al mismo, de una matriz $A\in\mathcal{M}_n(\mathbb{K})$, se basa en calcular una sucesion de vectores unitarios (para una cierta norma) $\{X_k\}_{k\in\mathbb{N}}$ y $n$ sucesiones numericas $\{\lambda^j_k\}_{k\in\mathbb{N}}$ mediante el siguiente algoritmo:
<ul>
    <li>
  dado $X_0\in\mathbb{C}^n-\{0\}$ unitario;</li>
    <li>
  para $k=0,1,2,\ldots$, se contruye
$$
Y_{k+1} = A\,X_k \quad \mbox{y} \quad X_{k+1} = \frac{1}{\|Y_{k+1}\|}\,Y_{k+1}\,;
$$
igualmente, siempre que tengan sentido, se calculan
$$
\lambda^j_{k+1} = \frac{(Y_{k+1})_j}{(X_k)_j}\,, \quad j=1,2,\ldots, n\,.
$$</li>
</ul>
    Sabemos tambien que bajo ciertas hipotesis (autovalor $\lambda_1$ dominante unico, excepto multiplicidad, buena eleccion del vector inicial, etc.) se obtienen resultados de convergencia en el siguiente sentido:
<ul>
    <li>se tiene la convergencia de normas
\[
\lim_{k\to\infty} \|Y_{k+1}\| = \lim_{k\to\infty} \|A\,X_k\| = |\lambda_1|\,;
\]</li>
    <li>se tiene la convergencia del cociente de componentes (cuando tengan sentido)
\[
\lim_{k\to\infty} \lambda^j_k = \lim_{k\to\infty} \frac{(Y_{k+1})_j}{(X_k)_j} = \lambda_1\,, \quad j=1,2,\ldots, n\,;
\]</li>
    <li>se tiene la convergencia de los vectores
$$
\lim_{k\to\infty} \left( \frac{\bar{\lambda}_1}{|\lambda_1|} \right)^k X_k
$$
hacia un autovector asociado al autovalor $\lambda_1$.</li>
</ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
  Elaboramos a continuacion un programa que implementa el algoritmo del metodo de la potencia. Dicho programa, de nombre <span style="font-family: Courier">potencia()</span>, tiene como argumentos de entrada, por este orden, la matriz <span style="font-family: Courier">A</span>, el vector inicial con el que comenzar las iteraciones <span style="font-family: Courier,monospace">X</span>, la norma <span style="font-family: Courier">norma</span> con la que realizar el proceso de normalizacion, el numero maximo de iteraciones <span style="font-family: Courier">itermax</span> superadas las cuales el proceso se detendra, y la tolerancia <span style="font-family: Courier">tol</span> que establece el test de parada. En caso de exito, los paramtros de salida son una variable booleana indicando que efectivamente se ha alcanzado una situacion de convergencia (en caso contrario se envia un mensaje explicativo de error), asi como los ultimos valores calculados de la sucesion de las normas de $Y_k$, de las sucesiones $\lambda^j_k$, $j=1,2,\ldots,n$ y de los vectores $X_k$.
    <br>
    En el algoritmo implementado se realizaran iteraciones mientras que el numero de iteraciones sea inferior al maximo establecido dado y el error sea superior o igual a la tolerancia dada, calculandose el error sobre el valor absoluto de la diferencia de las normas de $Y_{k+1}$ e $Y_k$. En un primer momento podemos hacer que el programa imprima bastante informacion durante las iteraciones; una vez que se conozca el funcionamiento del mismo, puede ser interesante imprimir menos informacion.
    </span></div>

In [ ]:
def potencia(A, X, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)

    if m != n or n != r or s != 1:
        return False, 'ERROR potencia: no se ejecuta el programa.', 0, 0

    k = 0
    error = tol
    normaold = 0.

    if A.dtype == complex or X.dtype == complex:
        lambdas = zeros(n, dtype=complex)
    else:
        lambdas = zeros(n, dtype=float)

    while k < itermax and error >= tol:
        k = k+1
        Y = A@X
        normanew = norma_vec(Y, norma)
        error = abs(normanew - normaold)

        for i in range(n):
            if abs(X[i, 0]) >= 1e-100:
                lambdas[i] = Y[i, 0]/X[i, 0]
            else:
                lambdas[i] = 0.

        X = Y/normanew

        print('Iteracion: k = ', k)
        print('Norma: ||A*X_k|| = ', normanew)
        print('Lambdas: lambdas_k = \n', lambdas)
        print('Vectores: X_k = \n', transpose(X))
        normaold = normanew

    if k == itermax and error >= tol:
        return False, 'ERROR potencia: no se alcanza convergencia.', 0, 0
    else:
        print('Metodo de la potencia: convergencia numerica alcanzada.')
        return True, normanew, lambdas, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 1.</b></span> Dada la matriz
$$
A = \left( \begin{array}{rrrr} -2 & 3 & -3 & 11 \\ -8 & 9 & -12 & 20 \\ -3 & 3 & -6 & 15 \\ -3 & 3 & -3 & 12 \end{array} \right)\,,
$$
calcular mediante el metodo de la potencia, si es posible, su autovalor dominante y un autovector asociado. Utilizar la norma infinito y tomar como vector inicial el primer vector de la base canonica de $\mathbb{C}^4$. Podemos poner un limite de 200 iteraciones y una tolerancia de $10^{-12}$.
    </span></div>

In [ ]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = \n", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = \n", X0)
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-12)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Una variante del metodo de la potencia es el <b>metodo de la potencia inversa</b>, que consiste en aplicar el metodo de la potencia a la matriz $A^{-1}$, en caso de que la misma exista (en caso contrario significa que es singular, y por tanto $\lambda=0$ es autovalor).
    <br>
    Elaboramos a continuacion un programa, de nombre <span style="font-family: Courier">potenciainv()</span>, con los mismos parametros de entrada y de salida que el anterior, que implemente dicho algoritmo.
    <br>
    Notamos que en la implementacion utilizaremos el metodo $L\,U$ para calcular la solucion de $Y_{k+1}=A^{-1}\,X_k$, por lo que habria que hacer una unica llamada al principio al programa <span style="font-family: Courier">facto_lu()</span> y llamadas a los programas <span style="font-family: Courier">descenso1()</span> y <span style="font-family: Courier">remonte</span> en cada iteracion.
    </span></div>

In [ ]:
def potenciainv(A, X, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)

    if m != n or n != r or s != 1:
        return False, 'ERROR potenciainv: no se ejecuta el programa.', 0, 0

    exito, LU = facto_lu(A)
    if not exito:
        return False, 'ERROR potenciainv: sin factorizacion LU.', 0, 0

    k = 0
    error = 1.
    normaold = tol

    if A.dtype == complex or X.dtype == complex:
        lambdas = zeros(n, dtype=complex)
    else:
        lambdas = zeros(n, dtype=float)

    while k < itermax and error >= tol:
        k = k+1
        exito, Y = descenso1(LU, X)
        exito, Y = remonte(LU, Y)

        if not exito:
            return False, 'ERROR potenciainv: sin factorizacion LU.', 0, 0

        normanew = norma_vec(Y, norma)
        error = abs(normanew - normaold)

        for i in range(n):
            if abs(X[i, 0]) >= 1e-100:
                lambdas[i] = Y[i, 0]/X[i, 0]
            else:
                lambdas[i] = 0.
        X = Y/normanew

        print('Iteracion: k = ', k)
        print('Norma: ||A-1*X_k|| = ', normanew)
        print('Lambdas: lambdas_k = ', lambdas)
        print('Vectores: X_k = ', transpose(X))
        normaold = normanew

    if k == itermax and error >= tol:
        return False, 'ERROR potenciainv: no se alcanza convergencia.', 0, 0
    else:
        print('Metodo de la potencia inversa: convergencia numerica alcanzada.')
        return True, normanew, lambdas, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 2.</b></span> Para la matriz dada en el caso anterior, calcular mediante el metodo de la potencia inversa, si es posible, su autovalor de modulo menor y un autovector asociado. Utilizar los mismos datos iniciales que en el caso anterior.
    </span></div>

In [ ]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = \n", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = \n", X0)
exito, normas, lambdas, X = potenciainv(A, X0, inf, 200, 1e-12)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Otra variante del metodo de la potencia es el metodo de la <b>potencia desplazada</b>, que consiste en aplicar el metodo de la potencia a la matriz $A-\mu\,I$, donde $\mu\in\mathbb{C}$ es un valor dado que nos permite mover la escala de los autovalores para localizar otros. Evidentemente se puede combinar el metodo de la potencia desplazada, con el metodo de la potencia inversa, dando lugar al metodo de la <b>potencia desplazada inversa</b>, que nos permite calcular el mas proximo al valor de $\mu$.
    <br>
    Los programas <span style="font-family: Courier">potenciades()</span> y <span style="font-family: Courier">potenciadesinv()</span> implementan dichos algoritmos; dichos programas deben tener un parametro de entrada adicional, que es el valor de $\mu$ (que lo ponemos como tercer argumento de entrada).
    </span></div>

In [ ]:
def potenciades(A, X, des, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n!= r or s != 1:
        return False, 'ERROR potenciades: no se ejecuta el programa.', 0, 0
    B = A - des*eye(n)
    exito, normanew, lambdas, X = potencia(B, X, norma, itermax, tol)
    return exito, normanew, lambdas, X

In [ ]:
def potenciadesinv(A, X, des, norma, itermax, tol):
    m, n = shape(A)
    r, s = shape(X)
    if m != n or n!= r or s != 1:
        return False, 'ERROR potenciadesinv: no se ejecuta el programa.', 0, 0
    B = A - des*eye(n)
    exito, normanew, lambdas, X = potenciainv(B, X, norma, itermax, tol)
    return exito, normanew, lambdas, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 3.</b></span> Para la misma matriz dada en los casos anteriores, calcular mediante el metodo de la potencia desplazada y sus variantes toda la informacion posible sobre sus autovalores y autovectores.
    </span></div>

In [ ]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = ", A)
X0 = array([[1], [0], [0], [0]])
print("X_0 = \n", X0)
exito, normas, lambdas, X = potenciades(A, X0, 9, inf, 200, 1e-10)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

In [ ]:
A = array([[-2, 3, -3, 11], [-8, 9, -12, 20], [-3, 3, -6, 15], [-3, 3, -3, 12]])
print("A = ", A)
X0 = array([[0], [0], [1], [0]])
print("X_0 = \n", X0)
exito, normas, lambdas, X = potenciadesinv(A, X0, 9, inf, 200, 1e-10)
if exito:
    print('Convergencia de las normas: ', normas)
    print('Convergencia de los cocientes:', lambdas)
    print('Convergencia de los vectores: ', X)
else:
    print(normas)

# lamnda = -12 pero como hemos desplazado 9 unidades, con lo que el autovalor es -12 + 9 = 3

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Caso 4.</b></span> Utilizando el metodo de la potencia y sus variantes, calcular todas la informacion posible sobre los autovalores y autovectores de las matrices siguientes:
$$
A = \left( \begin{array}{rrrr} 9 & 1 & -2 & 1 \\ 1 & 8 & -3 & -2 \\ -2 & -3 & 7 & -1 \\ 1 & -2 & -1 & 6 \end{array} \right)
\quad
A = \left( \begin{array}{rrrr} 1 & -1 & 3 & 4 \\ -1 & 4 & 0 & -1 \\ 3 & 0 & 0 & -3 \\ 4 & -1 & -3 & 1 \end{array} \right)
\quad
A = \left( \begin{array}{rrrr} 1 & 2 & 3 & 4 \\ 2 & 1 & 4 & 3 \\ 3 & 4 & 1 & 2 \\ 4 & 3 & 2 & 1 \end{array} \right)
$$
    </span></div>

In [ ]:
A = array([[9,1,-2,1],[1,8,-3,-2],[-2,-3,7,-1],[1,-2,-1,6]])
X0 = array([[1], [0], [0], [0]])
print("X_0 = ", X0)

exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-12)
if exito:
  print('Convergencia de las normas: ', normas)
  print('Convergencia de los cocientes:', lambdas)
  print('Convergencia de los vectores: ', X)
else:
  print(normas)

X_0 =  [[1]
 [0]
 [0]
 [0]]
Iteracion: k =  1
Norma: ||A*X_k|| =  9.0
Lambdas: lambdas_k = 
 [9. 0. 0. 0.]
Vectores: X_k = 
 [[ 1.          0.11111111 -0.22222222  0.11111111]]
Iteracion: k =  2
Norma: ||A*X_k|| =  9.666666666666666
Lambdas: lambdas_k = 
 [ 9.66666667 21.         18.         15.        ]
Vectores: X_k = 
 [[ 1.          0.24137931 -0.4137931   0.17241379]]
Iteracion: k =  3
Norma: ||A*X_k|| =  10.241379310344827
Lambdas: lambdas_k = 
 [10.24137931 15.85714286 14.         11.4       ]
Vectores: X_k = 
 [[ 1.          0.37373737 -0.56565657  0.19191919]]
Iteracion: k =  4
Norma: ||A*X_k|| =  10.696969696969697
Lambdas: lambdas_k = 
 [10.6969697  14.18918919 12.85714286 10.26315789]
Vectores: X_k = 
 [[ 1.          0.49575071 -0.67988669  0.18413598]]
Iteracion: k =  5
Norma: ||A*X_k|| =  11.039660056657222
Lambdas: lambdas_k = 
 [11.03966006 13.38857143 12.4         9.73846154]
Vectores: X_k = 
 [[ 1.          0.60123172 -0.76366436  0.16243264]]
Iteracion: k =  6
Norma:

In [ ]:
A = array([[1,-1,3,4],[-1,4,0,-1],[3,0,0,-3],[4,-1,-3,1]])
X0 = array([[1], [0], [0], [0]])
print("X_0 = ", X0)

exito, normas, lambdas, X = potenciades(A, X0, 1, inf, 200, 1e-12)
if exito:
  print('Convergencia de las normas: ', normas)
  print('Convergencia de los cocientes:', lambdas)
  print('Convergencia de los vectores: ', X)
else:
  print(normas)

In [ ]:
A = array([[1,2,3,4],[2,1,4,3],[3,4,1,2],[4,3,2,1]])
X0 = array([[0], [1], [-1], [0]])
print("X_0 = ", X0)

exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-12)
if exito:
  print('Convergencia de las normas: ', normas)
  print('Convergencia de los cocientes:', lambdas)
  print('Convergencia de los vectores: ', X)
else:
  print(normas)


X0 = array([[1], [0], [0], [0]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potencia(A, X0, inf, 200, 1e-12)
if exito:
  print('Convergencia de las normas: ', normas)
  print('Convergencia de los cocientes:', lambdas)
  print('Convergencia de los vectores: ', X)
else:
  print(normas)

X0 = array([[1], [0], [0], [0]])
print("X_0 = ", X0)
exito, normas, lambdas, X = potenciadesinv(A, X0, 0.2, inf, 200, 1e-12)

if exito:
  print('Convergencia de las normas: ', normas)
  print('Convergencia de los cocientes:', lambdas)
  print('Convergencia de los vectores: ', X)
else:
  print(normas)

X0 = array([[1], [-1], [0], [0]])
print("X_0 = ", X0)

exito, normas, lambdas, X = potenciades(A, X0, 10, inf, 200, 1e-12)
if exito:
  print('Convergencia de las normas: ', normas)
  print('Convergencia de los cocientes:', lambdas)
  print('Convergencia de los vectores: ', X)
else:
  print(normas)

X_0 =  [[ 0]
 [ 1]
 [-1]
 [ 0]]
Iteracion: k =  1
Norma: ||A*X_k|| =  3.0
Lambdas: lambdas_k = 
 [ 0. -3. -3.  0.]
Vectores: X_k = 
 [[-0.33333333 -1.          1.          0.33333333]]
Iteracion: k =  2
Norma: ||A*X_k|| =  3.3333333333333335
Lambdas: lambdas_k = 
 [-6.         -3.33333333 -3.33333333 -6.        ]
Vectores: X_k = 
 [[ 0.6  1.  -1.  -0.6]]
Iteracion: k =  3
Norma: ||A*X_k|| =  3.5999999999999996
Lambdas: lambdas_k = 
 [-4.66666667 -3.6        -3.6        -4.66666667]
Vectores: X_k = 
 [[-0.77777778 -1.          1.          0.77777778]]
Iteracion: k =  4
Norma: ||A*X_k|| =  3.777777777777778
Lambdas: lambdas_k = 
 [-4.28571429 -3.77777778 -3.77777778 -4.28571429]
Vectores: X_k = 
 [[ 0.88235294  1.         -1.         -0.88235294]]
Iteracion: k =  5
Norma: ||A*X_k|| =  3.8823529411764706
Lambdas: lambdas_k = 
 [-4.13333333 -3.88235294 -3.88235294 -4.13333333]
Vectores: X_k = 
 [[-0.93939394 -1.          1.          0.93939394]]
Iteracion: k =  6
Norma: ||A*X_k|| =  3.9393